badges.endorsed=Märke godkänt: %s.
badges.new=Märke erhållet: %s.
badges$badge.monsters_slain_1.title=Nybörjare på monsterjakt
badges$badge.monsters_slain_1.desc=Besegra 10 fiender i ett spel
badges$badge.monsters_slain_2.title=Skicklig monsterjägare
badges$badge.monsters_slain_2.desc=Besegra 50 fiender i ett spel
badges$badge.monsters_slain_3.title=Expert på monsterjakt
badges$badge.monsters_slain_3.desc=Besegra 100 fiender i ett spel
badges$badge.monsters_slain_4.title=Mästare på monsterjakt
badges$badge.monsters_slain_4.desc=Besegra 250 fiender i ett spel
badges$badge.monsters_slain_5.title=Stormästare i monsterjakt
badges$badge.monsters_slain_5.desc=Besegra 500 fiender i ett spel
badges$badge.gold_collected_1.title=Nybörjare på skattjakt
badges$badge.gold_collected_1.desc=Samla 250 guld i ett spel
badges$badge.gold_collected_2.title=Skicklig skattjägare
badges$badge.gold_collected_2.desc=Samla 1000 guld i ett spel
badges$badge.gold_collected_3.title=Expert på skattjakt
badges$badge.gold_collected_3.desc=Samla 2500 guld i ett spel
badges$badge.gold_collected_4.title=Mästare på skattjakt
badges$badge.gold_collected_4.desc=Samla 7500 guld i ett spel
badges$badge.gold_collected_5.title=Stormästare i skattjakt
badges$badge.gold_collected_5.desc=Samla 15 000 guld i en omgång
badges$badge.level_reached_1.title=Nybörjare på äventyr
badges$badge.level_reached_1.desc=Nå nivå 6
badges$badge.level_reached_2.title=Skicklig äventyrare
badges$badge.level_reached_2.desc=Nå nivå 12
badges$badge.level_reached_3.title=Expert på äventyr
badges$badge.level_reached_3.desc=Nå nivå 18
badges$badge.level_reached_4.title=Mästare på äventyr
badges$badge.level_reached_4.desc=Nå nivå 24
badges$badge.level_reached_5.title=Stormästare i äventyr
badges$badge.level_reached_5.desc=Nå nivå 30
badges$badge.all_weapons_identified.title=Vapenforskare
badges$badge.all_weapons_identified.desc=Identifiera alla vapen i din dagbok
badges$badge.all_armor_identified.title=Rustningsforskare
badges$badge.all_armor_identified.desc=Identifiera alla rustningar i din dagbok
badges$badge.all_wands_identified.title=Trollstavsforskare
badges$badge.all_wands_identified.desc=Identifiera alla trollspön i din dagbok
badges$badge.all_rings_identified.title=Ringforskare
badges$badge.all_rings_identified.desc=Identifiera alla ringar i din dagbok
badges$badge.all_artifacts_identified.title=Artefaktforskare
badges$badge.all_artifacts_identified.desc=Identifiera alla artefakter i din dagbok
badges$badge.all_potions_identified.title=Dryckesforskare
badges$badge.all_potions_identified.desc=Identifiera alla drycker i din dagbok
badges$badge.all_scrolls_identified.title=Skriftrullsforskare
badges$badge.all_scrolls_identified.desc=Identifiera alla skriftrullar i din dagbok
badges$badge.all_items_identified.title=Mästerforskare
badges$badge.all_items_identified.desc=Identifiera alla föremål i din dagbok
badges$badge.all_bags_bought.title=Packåsna
badges$badge.all_bags_bought.desc=Utöka packningen helt
badges$badge.death_from_fire.title=Bränd
badges$badge.death_from_fire.desc=Dö av eld
badges$badge.death_from_poison.title=Förgiftad
badges$badge.death_from_poison.desc=Dö av gift
badges$badge.death_from_gas.title=Kvävd
badges$badge.death_from_gas.desc=Dö av giftig gas
badges$badge.death_from_hunger.title=Utsvulten
badges$badge.death_from_hunger.desc=Dö av hunger
badges$badge.death_from_falling.title=Platt som en pannkaka
badges$badge.death_from_falling.desc=Dö av ett fall
badges$badge.death_from_enemy_magic.title=Zappad
badges$badge.death_from_enemy_magic.desc=Dog av en fiendes magiska attack
badges$badge.death_from_friendly_magic.title=Vådaskada
badges$badge.death_from_friendly_magic.desc=Dö av ditt eget magiska föremål
badges$badge.death_from_sacrifice.title=En värdig uppoffring
badges$badge.death_from_sacrifice.desc=Dö intill offerelden
badges$badge.death_from_grim_trap.title=Dödligt felsteg
badges$badge.death_from_grim_trap.desc=Dö av en döds- eller upplösningsfälla
badges$badge.death_from_all.title=Ännu en sorglig död
badges$badge.death_from_all.desc=Lås upp alla ”dödsorsak”-märken
badges$badge.boss_slain_1.title=Slemstädare
badges$badge.boss_slain_1.desc=Besegra bossen i slutet av kloakerna
badges$badge.boss_slain_2.title=Fängelsedirektör
badges$badge.boss_slain_2.desc=Besegra bossen i slutet av fängelset
badges$badge.boss_slain_3.title=Metallskrotare
badges$badge.boss_slain_3.desc=Besegra bossen i slutet av grottorna
badges$badge.boss_slain_4.title=Kungabesegrade
badges$badge.boss_slain_4.desc=Besegra bossen i slutet av staden
badges$badge.boss_slain_1_all_classes.title=Mångsysslare
badges$badge.boss_slain_1_all_classes.desc=Besegra den första bossen med varje hjälteklass
badges$badge.boss_slain_3_all_subclasses.title=Tusenkonstnär
badges$badge.boss_slain_3_all_subclasses.desc=Besegra den tredje bossen med alla hjälteunderklasser
badges$badge.boss_slain_remains.title=Smaka på hämnd!
badges$badge.boss_slain_remains.desc=Besegra en boss medan du håller en hjältes signaturföremål, när hjälten dödades av samma boss
badges$badge.strength_attained_1.title=Nybörjare i kroppsbyggnad
badges$badge.strength_attained_1.desc=Nå 12 baspoäng i styrka
badges$badge.strength_attained_2.title=Skicklig kroppsbyggare
badges$badge.strength_attained_2.desc=Nå 14 baspoäng i styrka
badges$badge.strength_attained_3.title=Expert i kroppsbyggnad
badges$badge.strength_attained_3.desc=Nå 16 baspoäng i styrka
badges$badge.strength_attained_4.title=Mästare i kroppsbyggnad
badges$badge.strength_attained_4.desc=Nå 18 baspoäng i styrka
badges$badge.strength_attained_5.title=Stormästare i kroppsbyggnad
badges$badge.strength_attained_5.desc=Nå 20 baspoäng i styrka
badges$badge.food_eaten_1.title=Nybörjargourmet
badges$badge.food_eaten_1.desc=Ät mat 10 gånger i ett spel
badges$badge.food_eaten_2.title=Skicklig gourmand
badges$badge.food_eaten_2.desc=Ät mat 20 gånger i ett spel
badges$badge.food_eaten_3.title=Expertgourmet
badges$badge.food_eaten_3.desc=Ät mat 30 gånger i ett spel
badges$badge.food_eaten_4.title=Mästargourmet
badges$badge.food_eaten_4.desc=Ät mat 40 gånger i ett spel
badges$badge.food_eaten_5.title=Stormästargourmet
badges$badge.food_eaten_5.desc=Ät mat 50 gånger i ett spel
badges$badge.item_level_1.title=Nybörjarförtrollare
badges$badge.item_level_1.desc=Skaffa ett föremål av nivå 3 eller högre
badges$badge.item_level_2.title=Skicklig förtrollare
badges$badge.item_level_2.desc=Skaffa ett föremål av nivå 6 eller högre
badges$badge.item_level_3.title=Expert på förtrollning
badges$badge.item_level_3.desc=Skaffa ett föremål av nivå 9 eller högre
badges$badge.item_level_4.title=Mästare på förtrollning
badges$badge.item_level_4.desc=Skaffa ett föremål av nivå 12 eller högre
badges$badge.item_level_5.title=Stormästare i förtrollning
badges$badge.item_level_5.desc=Skaffa ett föremål av nivå 15 eller högre
badges$badge.victory.title=Seger!
badges$badge.victory.desc=Skaffa Yendors amulett
badges$badge.victory_all_classes.title=Mästare på många områden
badges$badge.victory_all_classes.desc=Skaffa Yendors amulett med varje hjälteklass
badges$badge.mastery_combo.title=Gladiatorns raseri
badges$badge.mastery_combo.desc=Uppnå en kombination med 10 träffar
badges$badge.items_crafted_1.title=Nybörjaralkemist
badges$badge.items_crafted_1.desc=Tillverka 3 föremål via alkemi i ett spel
badges$badge.items_crafted_2.title=Skicklig alkemist
badges$badge.items_crafted_2.desc=Tillverka 8 föremål via alkemi i ett spel
badges$badge.items_crafted_3.title=Expert på alkemi
badges$badge.items_crafted_3.desc=Tillverka 15 föremål via alkemi i ett spel
badges$badge.items_crafted_4.title=Mästare på alkemi
badges$badge.items_crafted_4.desc=Tillverka 24 föremål via alkemi i ett spel
badges$badge.items_crafted_5.title=Stormästare i alkemi
badges$badge.items_crafted_5.desc=Tillverka 35 föremål via alkemi i ett spel
badges$badge.no_monsters_slain.title=Pacifist
badges$badge.no_monsters_slain.desc=Färdigställ en våning utan att besegra en enda fiende
badges$badge.grim_weapon.title=Den grimme liemannen
badges$badge.grim_weapon.desc=Besegra en fiende med ett dödligt vapen
badges$badge.piranhas.title=Okonventionell fiskare
badges$badge.piranhas.desc=Döda 6 pirayor i ett spel
badges$badge.boss_challenge_1.title=Felfri seger
badges$badge.boss_challenge_1.desc=Besegra kloakbossen utan att låta den använda sin laddningsattack eller läka sig i vatten
badges$badge.boss_challenge_2.title=Jag har dig!
badges$badge.boss_challenge_2.desc=Besegra fängelsebossen utan att träffas av fällor eller andra faror
badges$badge.boss_challenge_3.title=Utmanövrerad
badges$badge.boss_challenge_3.desc=Besegra grottbossen utan att bli attackerad eller skadad medan den är superladdad
badges$badge.boss_challenge_4.title=Inga vapen i hans närvaro
badges$badge.boss_challenge_4.desc=Besegra stadsbossen utan att någonsin direkt attackera honom med vapen, ringar, trollstavar eller skadliga besvärjelser
badges$badge.boss_challenge_5.title=Demonjägaren
badges$badge.boss_challenge_5.desc=Besegra slutbossen medan alla demonframmanare lever och utmaningen med tuffare bossar är aktiverad
badges$badge.games_played_1.title=Nybörjare i grottutforskning
badges$badge.games_played_1.desc=Spela 10 spel eller vinn ett spel
badges$badge.games_played_2.title=Skicklig grottutforskare
badges$badge.games_played_2.desc=Spela 25 spel eller vinn tre spel
badges$badge.games_played_3.title=Expert på fängelsehålor
badges$badge.games_played_3.desc=Spela 50 spel eller vinn fem spel
badges$badge.games_played_4.title=Mästare på fängelsehålor
badges$badge.games_played_4.desc=Spela 200 spel eller vinn 10 spel
badges$badge.games_played_5.title=Stormästare på fängelsehålor
badges$badge.games_played_5.desc=Spela 1000 spel eller vinn 25 spel
badges$badge.high_score_1.title=Nybörjare på poängjakt
badges$badge.high_score_1.desc=Avsluta en omgång med 5 000 poäng eller mer
badges$badge.high_score_2.title=Skicklig poängjagare
badges$badge.high_score_2.desc=Avsluta en omgång med 25 000 poäng eller mer
badges$badge.high_score_3.title=Expert på poängjakt
badges$badge.high_score_3.desc=Avsluta en omgång med 100 000 poäng eller mer
badges$badge.high_score_4.title=Mästare på poängjakt
badges$badge.high_score_4.desc=Avsluta en omgång med 250 000 poäng eller mer
badges$badge.high_score_5.title=Stormästare i poängjakt
badges$badge.high_score_5.desc=Avsluta en omgång med 1 000 000 poäng eller mer
badges$badge.researcher_1.title=Nybörjarforskare
badges$badge.researcher_1.desc=Fyll i 40 katalogposter i din dagbok
badges$badge.researcher_2.title=Skicklig forskare
badges$badge.researcher_2.desc=Fyll i 80 katalogposter i din dagbok
badges$badge.researcher_3.title=Expertforskare
badges$badge.researcher_3.desc=Fyll i 160 katalogposter i din dagbok
badges$badge.researcher_4.title=Mästerforskare
badges$badge.researcher_4.desc=Fyll i 320 katalogposter i din dagbok
badges$badge.researcher_5.title=Stormästare i forskning
badges$badge.researcher_5.desc=Fyll i alla katalogposter i din dagbok
badges$badge.catalog_one_equipment.title=Välutrustad
badges$badge.catalog_one_equipment.desc=Fyll i en katalogpost för varje sorts utrustningsföremål i dagboken
badges$badge.catalog_potions_scrolls.title=Fullt lager
badges$badge.catalog_potions_scrolls.desc=Identifiera alla vanliga drycker och skriftrullar i en runda
badges$badge.all_rare_enemies.title=Storviltsjägare
badges$badge.all_rare_enemies.desc=Fyll i tio katalogposter för sällsynta fiender i din dagbok
badges$badge.rodney.title=Inte så skrämmande längre
badges$badge.rodney.desc=Lär dig det sanna namnet på dvärgarnas kung
badges$badge.happy_end.title=Lyckligt slut
badges$badge.happy_end.desc=Ta Yendors amulett till ytan
badges$badge.happy_end_remains.title=Du klarade det också
badges$badge.happy_end_remains.desc=Ta en fallen hjältes signaturföremål till ytan
badges$badge.champion_1.title=Bronskämpe
badges$badge.champion_1.desc=Klara spelet med minst en aktiverad utmaning
badges$badge.champion_2.title=Silverkämpe
badges$badge.champion_2.desc=Klara spelet med minst tre aktiverade utmaningar
badges$badge.champion_3.title=Guldkämpe
badges$badge.champion_3.desc=Klara spelet med minst sex aktiverade utmaningar
badges$badge.unlock_mage.title=Magikern är upplåst!
badges$badge.unlock_mage.desc=Lås upp Magikern genom att använda en uppgraderingsskriftrulle
badges$badge.unlock_rogue.title=Tjuven är upplåst!
badges$badge.unlock_rogue.desc=Lås upp Tjuven genom att göra 10 överraskningsattacker i en omgång
badges$badge.unlock_huntress.title=Jägarinnan är upplåst!
badges$badge.unlock_huntress.desc=Lås upp Jägarinnan genom att träffa fiender med kastvapen 10 gånger i en omgång
badges$badge.unlock_duelist.title=Duellanten är upplåst!
badges$badge.unlock_duelist.desc=Lås upp Duellanten genom att utrusta ett vapen på nivå 2 eller högre utan styrkestraff
badges$badge.unlock_cleric.title=Prästen är upplåst!
badges$badge.unlock_cleric.desc=Lås upp Prästen genom att helt rena förbannelsen från en förbannad utrustningsdel
badges$badge.enemy_hazards.title=Säkerhetsrisk
badges$badge.enemy_hazards.desc=Besegra 10 fiender i ett spel med hjälp av terränghinder (fällor, växter eller avgrunder)
badges$badge.many_buffs.title=Så många färger
badges$badge.many_buffs.desc=Ha minst 10 ikoner för positiva eller negativa effekter aktiva samtidigt
badges$badge.pacifist_ascent.title=Pacifistisk uppstigning
badges$badge.pacifist_ascent.desc=Ta Yendors amulett till ytan utan att någonsin minska förbannelsens styrka
badges$badge.taking_the_mick.title=Driva med någon
badges$badge.taking_the_mick.desc=Ge slutbossen dödsstöten med en hacka på +20 eller högre
badges$badge.victory_random.title=Slumpmässig seger!
badges$badge.victory_random.desc=Skaffa Yendors amulett med en slumpmässig hjälte, talanguppgraderingar, underklass och rustningsförmåga

challenges.no_food=På diet
challenges.no_food_desc=Maten är redan knapp, men du måste också hålla koll på portionerna!\n\n- Mat och överflödshornet är en tredjedel så effektiva på att mätta\n- Andra källor till mättnad påverkas inte
challenges.no_armor=Tro är min rustning
challenges.no_armor_desc=Du behöver tro på dig själv, eftersom rustningen inte hjälper särskilt mycket!\n\n- Grundblockeringen minskas för all rustning utom tyg\n- All rustning får nu mycket lite blockering vid uppgradering\n- Jordväktarens försvarskraft minskas också kraftigt
challenges.no_healing=Farmafobi
challenges.no_healing_desc=Läkedrycker är onekligen praktiska, men tyvärr är du allergisk!\n\n- Läkedrycker, föremål som använder läkedrycker i sina recept och solfrukt förgiftar hjälten i stället för att läka\n- Instabila brygder kan inte slumpmässigt förgifta eller läka hjälten\n- Föremålen fungerar fortfarande normalt för andra varelser.
challenges.no_herbalism=Ödemark
challenges.no_herbalism_desc=Det verkar inte finnas rent vatten kvar i den här förbannade fängelsehålan …\n\n- Daggdroppar tas bort\n- Växter tas bort\n- Frön dyker fortfarande upp, men slår inte rot
challenges.swarm_intelligence=Svärmintelligens
challenges.swarm_intelligence_desc=Se upp, fängelsehålans monster blir smartare!\n\n- När fiender ser dig eller dina allierade drar de andra närliggande fiender till din position.\n- Räckvidden börjar på bara 2 rutor, men ökar med 2 för varje tur som fienden ser dig, upp till 12.\n- När siktlinjen bryts återställs lockningsräckvidden, även om avbrottet bara är kort, till exempel vid en dörr.
challenges.darkness=In i mörkret
challenges.darkness_desc=Det är ju trots allt en fängelsehåla!\n\n- Den normala synvidden minskas kraftigt\n- En fackla dyker upp på varje våning\n- Andra ljuskällor är en femtedel så effektiva
challenges.no_scrolls=Förbjudna runor
challenges.no_scrolls_desc=En viss runa är svårare att hitta. Tyvärr är det alltid den mest användbara.\n\n- Hälften av fängelsehålans uppgraderingsskriftrullar tas bort
challenges.champion_enemies=Fientliga kämpar
challenges.champion_enemies_desc=Du är inte den enda som kan gå upp i nivå!\n\nVanliga fiender har en chans på 1/8 att dyka upp med en särskild mästareffekt på våning 1, som ökar till 1/6 på våning 21.\n\n- Mästare vaknar om de dyker upp sovande\n- Hjälten vet när en mästare dyker upp\n- Mästare kan inte göras till allierade\n\nDet finns sex typer av mästarfiender:\n_Blossande (orange):_ +25 % närstridsskada, antänder vid träff, sprider lågor vid död, kan inte antända vattenrutor\n_Projicerande (lila):_ +25 % närstridsskada, +3 närstridsräckvidd\n_Antimagisk (grön):_ −50 % mottagen skada, immun mot magiska effekter\n_Jätte (blå):_ −80 % mottagen skada, +1 närstridsräckvidd, kan inte röra sig in i tunnlar\n_Välsignad (gul):_ fyrdubbel träffsäkerhet och undvikande\n_Växande (röd):_ +20 % träffsäkerhet, undvikande, skada och effektiv hälsa. Ökar med 1 % var fjärde tur.
challenges.stronger_bosses=Tuffare bossar
challenges.stronger_bosses_desc=Bossarna är mycket tuffare med den här utmaningen!\n\n_Goo:_ +20 % hälsa\n_-_ Läkning i vatten ökar till 3 per tur\n_-_ Pumpas upp på 1 tur i stället för 2\n_Tengu:_ +25 % hälsa\n_-_ Fas 1: fällorna är mycket dödligare\n_-_ Fas 2: förmågorna används oftare\n_DM-300:_ +33 % hälsa\n_-_ Pylonerna är tuffare och 3 aktiveras\n_-_ Förmågorna är kraftfullare och används oftare\n_-_ DM-300 är snabbare när den är superladdad\n_-_ Frilagda ledningar är dubbelt så vanliga\n_Dvärgkungen:_ +50 % hälsa\n_-_ Hantlangarna är starkare i alla faser\n_-_ Fas 1: snabbare förmågor och frammaningar\n_-_ Fas 2: 2 fler hantlangare per omgång\n_-_ Fas 3: dubbelt så mycket hälsa, snabbare frammaningar\n_Yog-Dzewa:_\n_-_ Två nävar frammanas samtidigt!\n_-_ +60 % laserskada\n_-_ Starkare hantlangare

rankings$record.something=Dödad av någonting
rankings$record.won=Fick Yendors amulett
rankings$record.ascended=Steg upp med amuletten!
