plants.blandfruitbush.name=faddfrukt
plants.blandfruitbush.desc=Den päronformade frukten från faddfruktbusken, en avlägsen släkting till rötbär, smakar som kompakt damm. Frukten är äcklig och mättar dåligt, men är inte giftig. Kanske går den att tillaga.
plants.blandfruitbush.discover_hint=Du kan hitta denna växt slumpmässigt i fängelsehålan.
plants.blandfruitbush$seed.name=frö från faddfrukt

plants.blindweed.name=blindogräs
plants.blindweed.desc=Vid beröring försvinner blindogräs i en stark ljusblixt. Blixten är tillräckligt stark för att desorientera i flera sekunder.
plants.blindweed.warden_desc=_Väktaren_ kanaliserar blindogräsets energi till ett tillfälligt hölje av osynlighet i stället för att desorienteras.
plants.blindweed$seed.name=frö från blindogräs

plants.mageroyal.name=mageroyal
plants.mageroyal.refreshed=Du känner dig återhämtad.
plants.mageroyal.desc=Mageroyalens taggiga blommor innehåller en kemikalie som är känd för sina starkt neutraliserande egenskaper. Allt som trampar på växten renas från många negativa effekter.
plants.mageroyal.warden_desc=Utöver den neutraliserande effekten blir _Väktaren_ tillfälligt immun mot alla områdesbundna effekter när hon trampar på mageroyal.
plants.mageroyal$seed.name=frö från mageroyal

plants.earthroot.name=jordrot
plants.earthroot.desc=När en varelse vidrör en jordrot skapar dess rötter en slags orörlig naturlig rustning runt om den.
plants.earthroot.warden_desc=Rötterna från en jordrotsväxt följer _Väktaren_ och ger henne rörlig barkrustning.
plants.earthroot$seed.name=frö från jordrot
plants.earthroot$armor.name=växtrustning
plants.earthroot$armor.desc=En sorts naturlig, orörlig rustning av bark och snöre.\n\nVäxtrustningen blockerar %d skada från varje fysiskt slag tills den till slut saknar hållbarhet och faller sönder.\n\nEftersom rustningen är orörlig bryts den sönder och försvinner när du förflyttar dig.\n\nÅterstående rustning: %d.

plants.fadeleaf.name=flyktlöv
plants.fadeleaf.desc=Alla varelser som rör ett flyktlöv teleporteras till en slumpmässig plats på den aktuella nivån.
plants.fadeleaf.warden_desc=Flyktlövens teleporteringseffekt är starkare för _Väktaren_ och förflyttar henne tillbaka till slutet av föregående fängelsehålenivå.
plants.fadeleaf$seed.name=frö från flyktlöv

plants.firebloom.name=eldblomma
plants.firebloom.desc=När något vidrör en eldblomma sätts det i lågor.
plants.firebloom.warden_desc=När _Väktaren_ trampar på en eldblomma genomsyras hon kortvarigt av lågor i stället för att skadas.
plants.firebloom$seed.name=frö från eldblomma

plants.icecap.name=ishatt
plants.icecap.desc=Vid beröring släpper en ishatt ut ett bloss av frysande pollen. Fryseffekten är mycket starkare om miljön är blöt.
plants.icecap.warden_desc=När _Väktaren_ trampar på en ishatt genomsyras hon kortvarigt av frost i stället för att skadas.
plants.icecap$seed.name=frö från ishatt

plants.plant.warden_desc=Den här växten har ingen särskild effekt när Väktaren använder den.
plants.plant.discover_hint=Du kan hitta denna växt slumpmässigt i fängelsehålan eller odla den från dess frö.
plants.plant$seed.seed_of=frö från %s
plants.plant$seed.ac_plant=PLANTERA
plants.plant$seed.info=Kasta fröet på platsen där du vill odla en växt.\n\n%s
plants.plant$seed$placeholder.name=frö

plants.rotberry.name=rötbär
plants.rotberry.desc=Bären från en ung rötbärsbuske smakar som ljuv, ljuv död. På några år växer busken till ännu ett röthjärta. När den trampas på avger ett ungt rötbär en liten puff av giftig gas.
plants.rotberry.warden_desc=Vanligtvis avger en rötbärsbuske bara lite gas när den trampas på, men _Väktaren_ kan utvinna energi ur den för att tillfälligt öka sin styrka!
plants.rotberry.discover_hint=Du kan odla växten från dess frö under ett visst uppdrag.
plants.rotberry$seed.name=frö från rötbär
plants.rotberry$seed.discover_hint=Du kan hitta detta föremål under ett specifikt uppdrag.

plants.sorrowmoss.name=vemossa
plants.sorrowmoss.desc=Vemossa är en blomma (inte en mossa) med knivskarpa kronblad, täckta med ett dödligt gift.
plants.sorrowmoss.warden_desc=När _Väktaren_ trampar på vemossa genomsyras hon kortvarigt av gift i stället för att skadas.
plants.sorrowmoss$seed.name=frö från vemossa

plants.starflower.name=stjärnblomma
plants.starflower.desc=Stjärnblomma är en sällsynt växt som sägs ge helig kraft åt den som rör vid den.
plants.starflower.warden_desc=Utöver att bli välsignad får _Väktaren_ en avsevärd mängd trollstavsladdning när hon trampar på en stjärnblomma.
plants.starflower$seed.name=frö från stjärnblomma

plants.stormvine.name=stormranka
plants.stormvine.desc=Gravitationen påverkar stormrankan märkligt och låter dess tunna blå rankor ”hänga” i luften. Allt som fångas i rankan påverkas av detta och desorienteras.
plants.stormvine.warden_desc=_Väktaren_ kan styra stormrankans gravitationseffekt och svävar kort när hon trampar på en.
plants.stormvine$seed.name=frö från stormranka

plants.sungrass.name=solgräs
plants.sungrass.desc=Solgräs är känt för savens långsamma men effektiva läkande egenskaper.
plants.sungrass.warden_desc=_Väktaren_ kan få läkande från nedtrampat solgräs även om hon rör sig bort från det.
plants.sungrass$seed.name=frö från solgräs
plants.sungrass$health.name=örtläkande
plants.sungrass$health.desc=Solgräs har utmärkta läkande egenskaper, men är mycket långsammare än en läkande trolldryck.\n\nOm du lämnar växten avbryts den läkande effekten.\n\nÅterstående läkande: %d.

plants.swiftthistle.name=kvicktistel
plants.swiftthistle.desc=När den trampas på accelererar kvicktisteln kort tidsflödet runt sig, så att den som trampar på den kan utföra flera handlingar omedelbart.
plants.swiftthistle.warden_desc=Utöver att få omedelbara handlingar får _Väktaren_ också en kort hastighetsökning när hon trampar på kvicktistel.
plants.swiftthistle$seed.name=frö från kvicktistel
plants.swiftthistle$timebubble.name=tidsbubbla
plants.swiftthistle$timebubble.desc=En liten bubbla av accelererad tid som låter handlingar utföras omedelbart. Attacker eller magianvändning bryter dock effekten.\n\nÅterstående turer: %s.
