items.heap.grave=Hjältens gravsten
items.heap.rip=Vila i frid


scenes.hallofheroesscene.title=Hjältarnas hall
scenes.hallofheroesscene.no_games=Det finns inga hjältar på den här sidan
scenes.hallofheroesscene.page=Sida %1$d/%2$d

scenes.heroselectscene.rename_hero=Byt namn på hjälte
scenes.heroselectscene.rename_title=Ange ett hjältenamn
scenes.heroselectscene.rename_desc=Detta används som standardnamn för hjälten.
scenes.heroselectscene.rename=Döp om
scenes.heroselectscene.revert=Återställ

scenes.supporterscene.gplay_msg=Om du gillar Shattered Pixel Dungeon och vill hjälpa mig att fortsätta utveckla spelet kan du gärna bli stödmedlem! Det finns även roliga kosmetiska tillägg som endast är tillgängliga för stödmedlemmar!\n\nTryck på någon av knapparna nedan om du vill veta mer.
scenes.supporterscene.loading=Läser in …
scenes.supporterscene.failed=Kunde inte läsa in betalningsinformationen!\n\nKontrollera att du är ansluten till internet.
scenes.supporterscene.silver=Silverstödjare
scenes.supporterscene.gold=Guldstödjare
scenes.supporterscene.shattered=Shattered-stödjare
scenes.supporterscene.purchased=Köpt!
scenes.supporterscene.pending=Väntar på betalning …

scenes.titlescene.thank_you=Tack!
scenes.titlescene.games_outdated_warn=Från och med nästa speluppdatering (%1$s) kräver Google Play Spel Android %2$s och inaktiveras därför på den här enheten.\n\nInga synkroniserade data går förlorade, men enheten kan inte synkronisera nya data eller låsa upp nya Google Play-prestationer.

ui.donationbutton.pls_1=Överväg gärna en donation
ui.donationbutton.pls_2=Donationer och belöningar
ui.donationbutton.pls_3=Donera och få belöningar!
ui.donationbutton.pls_4=Donationer och tillägg
ui.donationbutton.ty_1=Tack!
ui.donationbutton.ty_3=Tack för att du donerat!
ui.donationbutton.ty_2=Tack!


windows.wndanalytics.title=Dela speldata
windows.wndanalytics.policy=Fullständig policy för integritet
windows.wndanalytics.text=Du kan stödja Shattered Pixel Dungeon genom att dela speldata.\n\nInformationen är mycket användbar när beslut fattas om spelets utformning, så genom att spela och skicka data stödjer du spelet.\n\nIngen personligt identifierbar information samlas in och dataanvändningen är minimal.

windows.wndsupportertiers$tier1info.title=Silverstödjare
windows.wndsupportertiers$tier1info.intro=Silverstödjare får belöningar med fokus på spelets hjältar! Du kan när som helst uppgradera till en högre stödnivå.
windows.wndsupportertiers$tier1info.menu=Menyknapp för silverstödjare
windows.wndsupportertiers$tier1info.notes=Högst 5 egna anteckningar
windows.wndsupportertiers$tier1info.rename_title=Namnge hjälten
windows.wndsupportertiers$tier1info.rename_desc=Figurer och rankningslistan använder ditt namn!
windows.wndsupportertiers$tier1info.graves_title=Gravstenar
windows.wndsupportertiers$tier1info.graves_desc=Rester från fallna hjältar visas nu på en speciell gravsten med en unik gravskrift!
windows.wndsupportertiers$tier2info.title=Gyllene Stödjare
windows.wndsupportertiers$tier2info.intro=Utöver silverbelöningarna får guldstödjare fler alternativ för namnbyten och en stor utökning av spelets rankningslistor!
windows.wndsupportertiers$tier2info.silver=Alla silverbelöningar
windows.wndsupportertiers$tier2info.menu=Menyknapp för guldstödjare
windows.wndsupportertiers$tier2info.notes=Högst 10 egna anteckningar
windows.wndsupportertiers$tier2info.rename_title=Döp om utrustning
windows.wndsupportertiers$tier2info.rename_desc=Ge din favoritutrustning egna episka namn!
windows.wndsupportertiers$tier2info.hall_title=Hjältarnas hall
windows.wndsupportertiers$tier2info.hall_desc=Fyra separata rankningssidor med stöd för egna anteckningar!
windows.wndsupportertiers$tier3info.title=Shattered-stödjare
windows.wndsupportertiers$tier3info.intro=Shattered-stödjare får allt från de tidigare nivåerna samt en guldkant i hela spelet! Tack så mycket för ditt stöd!
windows.wndsupportertiers$tier3info.golden=Alla gyllene belöningar
windows.wndsupportertiers$tier3info.notes=Högst 20 egna anteckningar
windows.wndsupportertiers$tier3info.menu=Menyknapp för smaragdstödjare
windows.wndsupportertiers$tier3info.hall_title=Utökad hjältarnas hall
windows.wndsupportertiers$tier3info.hall_desc=Sex ytterligare sidor i hjältarnas hall!
windows.wndsupportertiers$tier3info.interface_title=Gyllene gränssnitt
windows.wndsupportertiers$tier3info.interface_desc=Spelets fönster och huvudgränssnitt får en glänsande guldkant!
windows.wndsupportertiers$tier3info.enable_gold=Aktivera gyllene gränssnitt
windows.wndsupportertiers$tier3info.disable_gold=Inaktivera gyllene gränssnitt
windows.wndsupportertiers$iconbutton.normal=Återställ standardikonen
windows.wndsupportertiers$iconbutton.silver=Välj silverikon
windows.wndsupportertiers$iconbutton.golden=Välj guldikon
windows.wndsupportertiers$iconbutton.shattered=Välj Shattered-ikon
windows.wndsupportertiers$paymentbutton.purchase=Köp – %s
windows.wndsupportertiers$paymentbutton.pending=Väntar på betalning …

windows.wndgame.rename_item=Byt namn på föremål
windows.wndgame.custom_note=Egen anteckning
windows.wndgame.select_item=Välj ett föremål
windows.wndgame.dialog_title=Ange ett föremålsnamn
windows.wndgame.dialog_rename=Byt namn
windows.wndgame.dialog_revert=Återställ

windows.wndgoogleplaygames.title=Google Play Games
windows.wndgoogleplaygames.text=Shattered Pixel Dungeon använder Google Play Games för extra funktioner!\n\nGenom att ansluta till Google Play Games kan Shattered Pixel Dungeon:\n- synkronisera rankningslistor och märken mellan enheter\n- låsa upp Google Play-prestationer\n\nDu kan koppla från när som helst och dataanvändningen hålls till ett minimum.
windows.wndgoogleplaygames.connect=Anslut
windows.wndgoogleplaygames.disconnect=Koppla från
windows.wndgoogleplaygames.sign_out_info=Du kan logga ut från Google Play Spel i enhetens inställningsmeny eller i appen Google Play Spel.
windows.wndgoogleplaygames.close=Stäng

windows.wndranking.copy=Kopiera till hjältarnas hall
windows.wndranking.move=Flytta
windows.wndranking.page=Sida %d
windows.wndranking.move_where=Till vilken sida i hjältarnas hall vill du flytta posten?
windows.wndranking.page_full=Sidan är full. Du måste först ta bort poster från den.
windows.wndranking.remove=Ta bort
windows.wndranking.remove_warn=Är du säker på att du vill ta bort posten från hjältarnas hall?\n\nOm den inte finns på din rankningssida förloras den permanent.
windows.wndranking.notes=Anteckningar
windows.wndranking.custom_note=Egen anteckning
windows.wndranking.save=Spara
windows.wndranking.cancel=Avbryt
windows.wndranking.already_there=Posten finns redan i hjältarnas hall.
windows.wndranking.copy_where=Till vilken sida i hjältarnas hall vill du kopiera posten?

windows.wndsettings$datatab.analytics=Dela speldata
windows.wndsettings$datatab.googleplaygames=Google Play Spel

windows.wndsupportprompt.please_consider=Om du uppskattar ShatteredPD och vill hjälpa mig att fortsätta utveckla spelet kan du gärna stödja det!
windows.wndsupportprompt.rating=_- Ge spelet ett ärligt betyg eller en recension._ Det ökar spelets synlighet, vilket hjälper fler att hitta det!
windows.wndsupportprompt.support=_- Stöd spelet direkt._ Genom att stödja spelet bidrar du direkt till utvecklingen av Shattered och får dessutom några tillägg som tack!
windows.wndsupportprompt.thank_you=Tack för din tid och lycka till i fängelsehålan!
windows.wndsupportprompt.rating_prompt=Lämna ett betyg eller omdöme
windows.wndsupportprompt.rating_info=_Tack!_ Du bör just ha fått en fråga i spelet om att lämna ett omdöme.\n\nOm du inte fick någon fråga kan du även lämna ett betyg eller omdöme direkt på spelets butikssida.
windows.wndsupportprompt.rating_direct=Gå till butikssidan
windows.wndsupportprompt.support_prompt=Öppna supporterskärmen

ui.customnotebutton.limit_support_text=Du kan också höja gränsen för egna anteckningar genom att bli stödmedlem!
ui.customnotebutton.limit_support_button=Få plats för fler anteckningar

bones.here_lies_nameless=Här vilar en namnlös %s.
bones.here_lies_named=Här vilar %1$s den %2$s.
bones.pacifist=En erkänd pacifist som omkom utan att ta någon annans liv.
bones.rats=En ansedd råttbekämpare som besegrade %d fiender innan hen omkom.
bones.crabs=En skicklig krabbkrossare som besegrade %d fiender innan hen omkom.
bones.undead=En skräck för explosiva odöda som besegrade %d fiender innan hen omkom.
bones.thieves=En jagare av galna tjuvar som besegrade %d fiender innan hen omkom.
bones.bats=En klippare av fladdermusvingar som besegrade %d fiender innan hen omkom.
bones.brutes=En krossare av gnollhjälmar som besegrade %d fiender innan hen omkom.
bones.monks=Erfaren i strid mot dvärgkrigare besegrade hen %d fiender innan hen omkom.
bones.golems=En förgörare av dvärgiska uppfinningar som besegrade %d fiender innan hen omkom.
bones.demons=En legendarisk demonjägare som besegrade %d fiender innan hen omkom.
bones.yog=En utmanare av en demongud som besegrade %d fiender innan hen omkom.
bones.forgot_waterskin=Det är synd att de i dödskampen glömde att dricka ur sitt vattenskinn.
bones.forgot_potion=Synd att hen i dödskampen glömde dricka en hälsodryck.
bones.rest_in_peace=Hen lämnar sina ägodelar i denna värld när hen går vidare till nästa, i hopp om att en annan hjälte kan undgå samma grymma öde.
