ui.customnotebutton.title=Lägg till egen anteckning
ui.customnotebutton.limit_title=Anteckningsgränsen har nåtts
ui.customnotebutton.limit_text=Du kan radera befintliga anteckningar för att göra plats för fler. Alla egna anteckningar kan visas i dagboksfönstret.
ui.customnotebutton.desc=Egna anteckningar låter dig skriva ned vad du vill i dagboken.\n\nDe kan bestå av bara text eller kopplas till en fängelsehålenivå, ett av dina föremål eller en sorts dryck, skriftrulle eller ring.
ui.customnotebutton.new_text=Ny textanteckning
ui.customnotebutton.new_text_title=Skriv en titel för den egna textanteckningen:
ui.customnotebutton.new_floor=Ny anteckning för fängelsehålans våning
ui.customnotebutton.new_floor_prompt=Välj en fängelsehålenivå att koppla anteckningen till.
ui.customnotebutton.new_floor_title=Skriv en titel för den egna anteckningen för _våning %d_:
ui.customnotebutton.new_inv=Ny anteckning för packningsföremål
ui.customnotebutton.new_inv_prompt=Välj ett föremål för anteckningen
ui.customnotebutton.new_item_title=Skriv en titel för den egna anteckningen om föremålet:\n_%s_
ui.customnotebutton.new_type=Ny anteckning för föremålstyp
ui.customnotebutton.new_type_prompt=Välj den sorts föremål som du vill koppla anteckningen till.
ui.customnotebutton$customnotewindow.edit_title=Redigera titel
ui.customnotebutton$customnotewindow.add_text=Lägg till text
ui.customnotebutton$customnotewindow.edit_text=Redigera text
ui.customnotebutton$customnotewindow.delete=Ta bort
ui.customnotebutton$customnotewindow.delete_warn=Är du säker på att du vill radera denna anpassade anteckning?
ui.customnotebutton$customnotewindow.confirm=Bekräfta
ui.customnotebutton$customnotewindow.cancel=Avbryt

ui.quickslotbutton.select_item=Lägg ett föremål på en snabbplats

ui.talentspane.tier=nivå %d
ui.talentspane.unlock_tier2=Nå nivå 6 för att låsa upp fler talanger.
ui.talentspane.unlock_tier3=Nå nivå 12 och använd föremålet från den andra bossen för att låsa upp fler talanger.
ui.talentspane.unlock_tier4=Nå nivå 20 och använd föremålet från den fjärde bossen för att låsa upp fler talanger.
ui.talentspane.random_title=Slumpa talanger
ui.talentspane.random_sure=Är du säker på att du vill spendera dessa talangpoäng slumpmässigt?
ui.talentspane.random_yes=Ja, använd dem alla.
ui.talentspane.random_one=Spendera bara en slumpmässigt.
ui.talentspane.random_no=Jag bestämmer mig senare.

ui.toolbar.quickslot_prompt=Välj en snabbplats
ui.toolbar.quickslot_select=Välj snabbplats
ui.toolbar.quickslot_assign=Tilldela snabbplats
ui.toolbar.quickslot_cancel=Avbryt
ui.toolbar.container_prompt=Välj en behållare
ui.toolbar.container_select=Välj behållare
ui.toolbar.container_cancel=Avbryt
ui.toolbar.container_empty=Den behållaren är tom!
ui.toolbar.item_prompt=Välj ett föremål
ui.toolbar.item_select=Välj föremål
ui.toolbar.item_use=Snabbanvänd föremål
ui.toolbar.item_cancel=Avbryt
ui.toolbar.examine_prompt=Tryck igen för att söka\nTryck på en ruta för att undersöka

ui.updatenotification.title=Uppdatera
ui.updatenotification$wndupdate.title=En uppdatering finns tillgänglig!
ui.updatenotification$wndupdate.versioned_title=Uppdatering tillgänglig: %s
ui.updatenotification$wndupdate.desc=Shattered Pixel Dungeon uppdateras regelbundet med omarbetningar av befintligt spelinnehåll eller med helt nytt innehåll!\n\nSpelbalansen förbättras också ofta i uppdateringar, så att vissa föremål, hjältar eller fiender inte blir för starka eller svaga.\n\nUppdateringar innehåller även programfelsrättningar och andra stabilitetsförbättringar.
ui.updatenotification$wndupdate.button=Gå till uppdateringssidan
