// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Svenska.
extension Strings {
    static let sv = Strings(
        statusIdleTooltip: "Vorssaint: normalt viloläge",
        statusActiveUntil: "Vorssaint: aktiv till",
        statusActiveIndefinite: "Vorssaint: aktiv tills vidare",
        menuEnableAwake: "Aktivera Håll vaken",
        menuDisableAwake: "Inaktivera Håll vaken",
        menuActivateFor: "Aktivera under…",
        menuSettings: "Inställningar…",
        menuAbout: "Om Vorssaint",
        menuQuit: "Avsluta Vorssaint",
        menuHide: "Göm Vorssaint",
        menuHideOthers: "Göm övriga",
        menuShowAll: "Visa alla",
        menuEdit: "Redigera",
        menuUndo: "Ångra",
        menuRedo: "Gör om",
        actionClear: "Rensa",
        actionRemove: "Ta bort",
        actionBack: "Tillbaka",
        actionSearch: "Sök",
        actionMute: "Stäng av ljud",
        actionUnmute: "Slå på ljud",
        actionPlay: "Spela",
        actionPause: "Pausa",
        menuCut: "Klipp ut",
        menuCopy: "Kopiera",
        menuPaste: "Klistra in",
        menuSelectAll: "Markera allt",
        menuWindow: "Fönster",
        menuMinimize: "Minimera",
        menuZoom: "Zooma",
        menuClose: "Stäng",

        minutes15: "15 minuter",
        minutes30: "30 minuter",
        hour1: "1 timme",
        hours2: "2 timmar",
        hours4: "4 timmar",
        hours8: "8 timmar",
        indefinitely: "Tills vidare",
        indefinite: "Obestämd",

        panelSettings: "Inställningar",
        panelQuit: "Avsluta",
        panelHotkeyHint: "Kortkommandot växlar",

        keepAwakeTitle: "Håll vaken",
        keepAwakeEndsIn: "Slutar om",
        keepAwakeUntilDisabled: "Aktiv tills du stänger av den",
        keepAwakeNormalRules: "Datorn följer sina vanliga energisparregler",
        keepAwakeUntilLabel: "Till",
        keepAwakeUntilStart: "Starta",
        keepAwakeOptions: "Alternativ",
        keepAwakeMouseJiggle: "Rör pekaren lite",
        keepAwakeMouseJiggleCaption: "Flyttar pekaren lite med valt intervall under en session.",
        keepAwakeMouseJiggleInterval: "Intervall",
        keepAwakeActiveIconLabel: "Aktiv ikon",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kaffe",
        keepAwakeActiveIconEye: "Öga",
        keepAwakeActiveIconMoon: "Måne",
        keepAwakeActiveIconLight: "Glödlampa",
        keepAwakeIconTintLabel: "Färg på aktiv ikon",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Grön",
        keepAwakeIconTintBlue: "Blå",
        keepAwakeIconTintPurple: "Lila",
        keepAwakeIconTintPink: "Rosa",
        keepAwakeIconTintNone: "Ingen färg",
        durationLabel: "Varaktighet",
        clamshellTitle: "Fortsätt med locket stängt",
        clamshellOnCaption: "Viloläget är helt avstängt. Tänk på strömförbrukningen",
        clamshellNeedsSession: "Gäller när Håll vaken är aktivt",
        clamshellReady: "Klar. Växlar utan lösenord",
        clamshellNeedsPassword: "Ber om administratörslösenordet en gång",

        systemSection: "System",
        temperatures: "Temperaturer",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batteri",
        usageSection: "Maskinvaruanvändning",
        memorySection: "Minne",
        memoryPressure: "Tryck",
        memorySwapUsed: "Använt växlingsutrymme",
        memoryCompressed: "Komprimerat",
        memoryCachedFiles: "Cachelagrade filer",
        pressureNormal: "Normal",
        pressureWarning: "Varning",
        pressureCritical: "Kritiskt",
        monitorUnavailable: "Sensorer är inte tillgängliga på den här datorn",
        energyAppsTitle: "Appar med hög energiförbrukning",
        energyAppsIdle: "Ingen hög energiförbrukning",

        notifySessionEndedTitle: "Sessionen är slut",
        notifySessionEndedBody: "Tiden är slut. Datorn återgår till normalt viloläge.",
        notifyBatteryTitle: "Vorssaint har inaktiverats",
        notifyBatteryBody: "Låg batterinivå. Normalt viloläge har återställts för att skydda laddningen.",
        adminPromptClamshellOn: "Vorssaint behöver ditt lösenord för att hålla datorn igång med locket stängt.",
        adminPromptClamshellOff: "Vorssaint behöver ditt lösenord för att återställa datorns normala viloläge.",
        adminPromptRecover: "Vorssaint avslutades medan datorns viloläge var avstängt. Ange lösenordet för att återställa normalt viloläge.",
        adminPromptUpdate: "Vorssaint behöver ditt lösenord för att installera uppdateringen.",
        adminPromptSudoersInstall: "Vorssaint skapar en begränsad regel (endast pmset disablesleep) för att växla läge med stängt lock utan lösenord. Detta är enda gången lösenordet behövs.",
        adminPromptSudoersRemove: "Vorssaint tar bort regeln för stängt lock utan lösenord.",

        settingsTitle: "Vorssaint-inställningar",
        tabGeneral: "Allmän",
        tabEnergy: "Energi",
        tabMouse: "Mus & Styrplatta",
        tabSwitcher: "Switcher",
        tabAdvanced: "Avancerad",
        tabAbout: "Om",
        tabReleaseNotes: "Vad är nytt",
        releaseNotesOnUpdateToggle: "Visa vad som är nytt efter uppdatering",
        minimalWindowPreviews: "Minimala förhandsvisningar",
        minimalWindowPreviewsCaption: "Dölj titlar, knappar och dekorativa detaljer i Dock och switcher-förhandsvisningar. Urvalet förblir synligt.",
        previewSizeLabel: "Förhandsgranskningsstorlek",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Stor",
        previewSizeXLarge: "Extra large",
        settingsGroupFeatures: "Drag",
        advancedResetSection: "Behörigheter",
        advancedResetDescription: "Tar bort varje behörighet du gett Vorssaint (tillgänglighet, skärminspelning, fullständig diskåtkomst och andra), inloggningsobjektet och regeln med stängt lock. Användbart att börja om på nytt eller innan du avinstallerar. Appen förblir installerad.",
        advancedClearButton: "Rensa alla behörigheter",
        advancedCleared: "Behörigheter rensades.",
        advancedClearFailed: "Vissa behörigheter eller regeln med stängt lock kunde inte tas bort. Försök igen och tillåt lösenordsbegäran om den visas.",
        advancedClearConfirmTitle: "Rensa alla behörigheter?",
        advancedClearConfirmBody: "Funktioner som behöver behörigheter slutar fungera tills du beviljar dem igen. Dina inställningar behålls.",
        advancedUninstallSection: "Avinstallera",
        advancedUninstallDescription: "Gör allt ovanstående, tar sedan bort inställningarna och flyttar Vorssaint till papperskorgen och lämnar ingenting efter sig. Appen avslutas när den är klar. Du kan installera om när som helst.",
        advancedUninstallButton: "Avinstallera Vorssaint helt",
        advancedUninstallConfirmTitle: "Avinstallera Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint kommer att rensa sina behörigheter, ta bort sina inställningar och flytta till papperskorgen och sedan avsluta. Detta kan inte ångras från appen, men det stannar i papperskorgen tills du tömmer det.",
        advancedUninstallFailedTitle: "Avinstallationen stoppades",
        advancedUninstallFailedBody: "Vorssaint kunde inte återställa en systeminställning som den ändrade: viloläge, fläkthastighet, musacceleration eller rymdordning. Ingenting togs bort. Försök igen och tillåt lösenordsbegäran om den visas.",

        launchAtLogin: "Starta vid inloggning",
        languageLabel: "Språk",
        menuBarSection: "Menyraden",
        showCountdown: "Visa återstående tid bredvid ikonen",
        globalHotkeySection: "Global genväg",
        hotkeyToggle: "Aktivera genväg för \"Håll dig vaken\"",
        hotkeyCaption: "Fungerar i alla appar, inga extra behörigheter.",

        sessionSection: "Session",
        defaultDurationLabel: "Standardvaraktighet",
        keepAwakeAutoStart: "Håll dig vaken när Vorssaint öppnar",
        keepAwakeAutoStartCaption: "Startar en session med standardlängden.",
        batteryProtectionSection: "Batteriskydd",
        batteryDisableBelow: "Inaktivera när batteriet sjunker under",
        batteryNever: "Aldrig",
        batteryProtectionCaption: "Håller en bortglömd session från att ladda ur MacBook-batteriet.",
        clamshellSection: "Stängt lock",
        configuring: "Konfigurerar...",
        sudoersFailed: "Det gick inte att aktivera läget med stängt lock. Försök igen.",
        clamshellExplanation: "\"Fortsätt med locket stängt\" inaktiverar sömn helt medan \"Keep awake\" är aktivt och återställs automatiskt när sessionen avslutas eller appen avslutas. Föredrar att använda den inkopplad.",
        dimScreenOnLidCloseTitle: "Dim displayen till noll",
        dimScreenOnLidCloseCaption: "Dämpar skärmen när locket stängs och återställer ljusstyrkan när den öppnas.",

        scrollSection: "Scrollar",
        invertMouseScroll: "Invertera musrullning",
        invertMouseScrollCaption: "Vänder om mushjulets riktning.",
        scrollTrackpadNote: "Styrplattan är orörd: den håller macOS naturlig rullning.",
        scrollActiveNow: "Inverterar musrullning just nu",
        mouseNavigationActiveNow: "Sidoknapparna är aktiva just nu",
        smoothScrollName: "Smidig rullning",
        smoothScrollCaption: "Förvandlar varje mushjulssteg till ett kort, mjukt glid. Styrplattan påverkas inte.",
        smoothScrollStepLabel: "Scrollhastighet",
        mouseNavigationSection: "Navigering",
        mouseNavigationEnable: "Använd sidoknapparna för bakåt och framåt",
        mouseNavigationCaption: "Förvandlar musens bakåt- och framåtknappar till navigeringskommandon i Finder, webbläsare och kompatibla appar.",
        middleClickSection: "Mittklick på styrplattan",
        middleClickEnable: "Ett klick med tre fingrar fungerar som mittklick",
        middleClickEnableCaption: "Att trycka på styrplattan med tre fingrar fungerar som ett mushjulsklick: öppna länkar i en ny flik, stäng flikar och allt annat som mittknappen gör.",
        middleClickDragConflict: "macOS-drag med tre fingrar är aktiverat och använder tre fingrar, så klicka med fyra fingrar för mittklicket. För att använda tre, inaktivera drag med tre fingrar i Systeminställningar under Tillgänglighet, Pekarkontroll, Alternativ för styrplatta.",
        middleClickNoTrackpad: "Kan inte läsa styrplattan. Anslut en styrplatta som stöds.",
        middleClickTapPicker: "Ett lätt tryck klickar också",
        middleClickTapOff: "Av",
        middleClickTapThreeFingers: "3 fingrar",
        middleClickTapFourFingers: "4 fingrar",
        middleClickTapCaption: "Ett lätt tryck med så många fingrar, utan att trycka, avfyrar också mittklicket. Att glida räknas aldrig. Om macOS trefingertrycket är tilldelat till Slå upp, stäng av det så att båda inte avfyras samtidigt.",
        quickToolsTab: "Snabb panel",
        quickToolShortcutToggle: "Global genväg",
        ocrName: "Kopiera text från skärmen",
        ocrCaption: "Välj ett område på skärmen och den igenkända texten kopieras, redo att klistras in.",
        ocrCopied: "Text kopierad",
        ocrNoText: "Ingen text hittades",
        colorPickerName: "Färgväljare",
        colorPickerCaption: "Ta tag i färgen på valfri pixel på skärmen och kopiera den i ditt favoritformat.",
        colorPickerFormatLabel: "Kopierat format",
        colorPickerBareHexToggle: "Kopiera utan prefixet #",
        colorPickerPickNow: "Välj färg",
        micMuteName: "Stäng av mikrofonen",
        micUnmuteName: "Slå på mikrofonen",
        micMuteCaption: "Klipper av Mac-mikrofonen med ett klick eller genväg, över alla appar.",
        micMutedHUD: "Mikrofon avstängd",
        micUnmutedHUD: "Stäng av",
        micMutePartialHUD: "Vissa mikrofoner kunde inte stängas av",
        micUnmutePartialHUD: "Vissa mikrofoner är fortfarande avstängda",
        micMuteMenuBarToggle: "Visa i menyraden när ljudet är avstängt",
        micMuteMenuBarCaption: "En röd överkryssad mikrofon visas bredvid appens ikon i menyraden medan den här funktionen tystar den.",
        pastePlainName: "Klistra in som vanlig text",
        pastePlainCaption: "Klistrar in det du kopierade utan färger, typsnitt eller formatering. Originalet stannar på urklippet.",
        launcherName: "Snabb panel",
        launcherCaption: "En flytande panel med dina favoritverktyg, framkallad av en genväg var som helst.",
        launcherOpenNow: "Öppna snabbpanelen",
        launcherEditHint: "Använd tune-knappen för att välja, dölja och dra runt verktygen.",
        launcherEmptyState: "Alla verktyg är dolda. Använd tune-knappen för att lägga till dem igen.",
        launcherAddSection: "Lägg tillbaka",
        launcherKeysHint: "Pilarna navigerar, Enter öppnas, 1 till 9 öppnas direkt",

        switcherSection: "Fönsterbyte",
        switcherEnable: "Använd Vorssaint switcher",
        switcherEnableCaption: "Växla mellan appar och fönster, inklusive minimerade fönster och flera fönster från samma app.",
        switcherUsageHint: "Håll ned genvägen för att navigera; släpp för att aktivera fönstret. Skift eller ← går tillbaka; W stänger fönstret; Q avslutar appen; Esc avbryter.",
        switcherNoWindows: "Inga öppna fönster",
        switcherIconRowMode: "Visa %@ med stora ikoner",
        switcherIconRowModeCaption: "Visar en ikon per app med appens fönsterförhandsvisningar ovanför.",
        switcherSimpleModeCaption: "Visar appikoner och fönstertitlar, utan förhandsgranskning eller skärmdump av växlaren.",
        switcherShortcutHintApps: "Appar",
        switcherShortcutHintWindows: "Windows",
        switcherWindowShortcutCaption: "Öppnar en switcher för den främre appens fönster. Medan omkopplaren är öppen hoppar du mellan den valda appens fönster.",
        switcherTakeOverSystemShortcuts: "Byt ut macOS ⌘Tab och ⌘`",
        switcherTakeOverSystemShortcutsCaption: "Inaktiverar den matchande macOS-appen och fönstergenvägarna endast när Vorssaints switcher är aktiv. Alla appar som körs förblir tillgängliga.",
        switcherAppearanceDelay: "Utseendeförsening",
        switcherAppearanceDelayCaption: "Hur länge genvägen måste hållas innan växlaren visas.",
        switcherInstantSelection: "Omedelbart urval",
        switcherInstantSelectionCaption: "Flyttar markeringen och rullningspositionen omedelbart när du bläddrar i appar och fönster.",
        switcherMergeTabs: "Visa en post per app",
        switcherMergeTabsCaption: "Komprimerar alla en apps fönster till en post i switchern, istället för en post per fönster.",
        switcherWindowlessApps: "Appar utan öppet fönster",
        switcherWindowlessAppsCaption: "Väljer vilka appar som körs utan fönster alls som visas i switchern.",
        switcherWindowlessAppsOff: "Visa inte",
        switcherWindowlessAppsFinder: "Endast Finder",
        switcherWindowlessAppsAll: "Alla appar",
        switcherNoOpenWindow: "Inget öppet fönster",
        switcherOtherDesktop: "Andra skrivbord",
        dockPreviewName: "Dock förhandsgranska",
        dockPreviewEnable: "Förhandsgranska fönster från Dock",
        dockPreviewEnableCaption: "Håll muspekaren över en öppen app i Dock för att se dess fönster och klicka sedan på den du vill ha.",
        dockPreviewCurrentSpaceOnlyCaption: "När av, visar fönster från alla skrivbord. Att välja ett fönster på ett annat skrivbord tar dig dit.",
        dockPreviewBackgroundOpacity: "Panelbakgrund",
        dockPreviewBackgroundOpacityCaption: "Vrid ner den för att se mer av vad som sitter bakom panelen.",
        dockPreviewBackgroundOpacityGlassCaption: "Liquid Glass är på, så panelens transparens ställs in i Systeminställningar > Utseende.",
        dockPreviewOpenDelay: "Öppen fördröjning",
        dockPreviewOpenDelayCaption: "Hur länge pekaren måste vila på en ikon innan dess panel öppnas.",
        dockPreviewQuitAppOnClose: "Avsluta appen med ×-knappen",
        dockPreviewQuitAppOnCloseCaption: "I Dock Preview avslutar × hela appen istället för att bara stänga det fönstret.",
        dockPreviewKeepDockVisible: "Håll dockan synlig (experimentell)",
        dockPreviewKeepDockVisibleCaption: "Pausar automatiskt dölj medan förhandsgranskningen är öppen och återställer den när du lämnar. Kan ändra storlek på fönster. Om appen avbryts öppnar du den igen för att återställa Dock.",
        dockPreviewOrderByCreation: "Beställ fönster efter skapandetid",
        dockPreviewOrderByCreationCaption: "Visa äldre fönster först istället för de du använde senast.",
        dockClickMinimize: "Klicka på Dock-ikonen för att minimera",
        dockClickMinimizeCaption: "Den aktiva appens fönster minimeras när du klickar på dess Dock-ikon. Klicka igen för att ta tillbaka dem.",
        dockClickCycleWindows: "Klicka på Dock-ikonen för att växla mellan fönster",
        dockClickCycleWindowsCaption: "Klicka på en aktiv apps Dock-ikon för att rotera genom dess fönster, som ⌘`.",
        dockPreviewActiveNow: "Aktiv i Dock",
        dockPreviewDockUnavailable: "Kunde inte läsa Dock-objekt.",
        dockPreviewAutohideBeta: "Beta. Du kan stöta på några buggar.",
        dockPreviewOpenWindow: "Öppna fönstret",
        dockPreviewCloseWindow: "Stäng fönstret",
        dockPreviewMinimizeWindow: "Minimera fönstret",
        dockPreviewRestoreWindow: "Återställ fönster",
        dockPreviewPinPanel: "Fäst förhandsgranskning",
        dockPreviewUnpinPanel: "Lossa förhandsgranskningen",
        dockPreviewPinned: "Fäst",
        dockPreviewClosePanel: "Stäng förhandsvisning",
        dockPreviewPreviousWindow: "Föregående fönster",
        dockPreviewNextWindow: "Nästa fönster",

        cutPasteName: "Klipp & klistra",
        cutPasteEnable: "Klipp ut och klistra in filer i Finder",
        cutPasteEnableCaption: "Använd ⌘X för att klippa och ⌘V för att flytta filer och mappar i Finder.",
        cutPasteShowHUD: "Visa flytande panel",
        cutPasteShowHUDCaption: "Visa en flytande indikator med klippfilerna medan Finder är aktivt.",
        cutPasteHowTitle: "Hur man använder",
        cutPasteStep1: "Välj objekt i Finder och tryck på ⌘X för att klippa ut dem.",
        cutPasteStep2: "Öppna målmappen och tryck på ⌘V för att flytta dem dit.",
        cutPasteTextNote: "I textfält (som när du byter namn) fortsätter ⌘X och ⌘V att fungera som vanligt.",
        cutPasteActiveNow: "Klar att klippa i Finder",
        cutPasteAutomationNote: "Första gången ber macOS om tillåtelse att styra Finder.",
        cutReadyTitle: "Klipp ut",
        cutReadyHint: "i målmappen för att flytta",
        cutCancel: "Avbryt klippning",
        cutDoneTitle: "Rörd!",
        cutMovedSingular: "1 objekt har flyttats",
        cutMovedPluralFormat: "%d objekt har flyttats",
        cutSomeFailed: "Vissa objekt kunde inte flyttas",
        cutMovingTitle: "Rörlig…",
        cutMovingCountFormat: "%d av %d",

        autoQuitName: "Sluta på nära håll",
        autoQuitEnable: "Avsluta en app när dess sista fönster stängs",
        autoQuitEnableCaption: "Om du stänger en apps sista fönster avslutas den också.",
        autoQuitActiveNow: "Aktiv nu",
        autoQuitHowTitle: "Hur det fungerar",
        autoQuitStep1: "Stäng appens senaste fönster (⌘W eller den röda knappen).",
        autoQuitStep2: "Appen avslutas av sig själv. \"Spara ändringar?\" dialogrutor visas fortfarande.",
        autoQuitPredictableNote: "Appar som normalt körs utan fönster avslutas aldrig.",
        autoQuitOngoingWorkNote: "Vissa appar stänger sitt sista fönster medan de fortsätter att arbeta, till exempel en skärminspelning när inspelningen startar. De avslutas också, såvida de inte finns på listan över undantag.",
        autoQuitExceptionsTitle: "Undantag",
        autoQuitExceptionsCaption: "Appar på den här listan förblir öppna även utan fönster.",
        autoQuitExceptionsEmpty: "Inga undantag",
        autoQuitAddApp: "Lägg till app...",

        uninstallerName: "Avinstallationsprogram",
        uninstallerEnableCaption: "Tar bort en app tillsammans med cachar, inställningar, loggar och rester som den lämnar efter sig.",
        uninstallerStep1: "Dra en app till Inställningar eller välj en från listan.",
        uninstallerStep2: "Granska filerna som hittats och hur mycket utrymme de tar.",
        uninstallerStep3: "Flytta det du vill till papperskorgen. Ingenting raderas permanent.",
        uninstallerMenuItem: "Avinstallera en app...",
        uninstallerDropTitle: "Dra en app hit",
        uninstallerDropSubtitle: "eller välj en att skanna",
        uninstallerChoose: "Välj app...",
        uninstallerPickerTitle: "Välj app",
        uninstallerPickerSearch: "Sök appar",
        uninstallerPickerEmpty: "Inga appar hittades",
        uninstallerEmptyNote: "Ingenting tas bort utan din bekräftelse.",
        uninstallerFDANote: "Ge full diskåtkomst för en mer grundlig genomsökning.",
        uninstallerFDAGrant: "Ge åtkomst...",
        uninstallerFDAHint: "Slå på Vorssaint i listan. Om det inte finns där, klicka på + och välj Vorssaint från Applications. Åtkomsten gäller endast efter att du öppnat appen igen.",
        uninstallerFDARelaunch: "Starta om nu",
        uninstallerScanning: "Skannar filer...",
        uninstallerRemoving: "Flyttar till papperskorgen...",
        uninstallerFoundTitle: "hittade",
        uninstallerSelectedFormat: "%d av %d har valts",
        uninstallerRemove: "Flytta till papperskorgen",
        uninstallerCancel: "Avboka",
        uninstallerConfirmationExpired: "Denna bekräftelse är inte längre giltig. Granska de aktuella objekten och bekräfta igen.",
        uninstallerDoneTitle: "Gjort!",
        uninstallerFreedFormat: "%@ har tagits bort",
        uninstallerSomeFailed: "Vissa objekt kunde inte flyttas till papperskorgen.",
        uninstallerFailedNeedsFDA: "Appdata i sandlåde kan endast flyttas med full diskåtkomst. Administratörslösenordet står inte för det.",
        uninstallerFailedMoreFormat: "och %d till",
        uninstallerAnother: "Avinstallera en annan",
        uninstallerCatApp: "Ansökan",
        uninstallerCatSupport: "Stöd",
        uninstallerCatCaches: "Cacher",
        uninstallerCatPreferences: "Inställningar",
        uninstallerCatContainers: "Behållare",
        uninstallerCatLogs: "Loggar",
        uninstallerCatState: "Sparat tillstånd",
        uninstallerCatOther: "Andra",
        uninstallerCommandBarBrowseTitle: "Avinstallera applikation",
        uninstallerCommandBarToggle: "Visa i kommandoraden",
        uninstallerCommandBarCaption: "Välj och avinstallera appar i kommandofältet.",
        uninstallerCommandBarFinderTitle: "Avinstallera app vald i Finder",
        uninstallerSelectionUnavailable: "Välj en app som kan tas bort i Finder, eller välj en annan från listan.",

        urlCleanerName: "Rengör URL",
        urlCleanerEnable: "Rengör webbadresser när du kopierar dem",
        urlCleanerEnableCaption: "Tar bort spårningsparametrar från en länk i samma ögonblick som den når urklippet.",
        urlCleanerActiveNow: "Aktiv nu",
        urlCleanerManualTitle: "Rengör nu",
        urlCleanerInputPlaceholder: "Klistra in en URL",
        urlCleanerOutputPlaceholder: "Den rena webbadressen visas här",
        urlCleanerPasteButton: "Klistra in",
        urlCleanerCopyButton: "Kopiera",
        urlCleanerClearButton: "Rensa fält",
        urlCleanerNoURL: "Klistra in en giltig URL.",
        urlCleanerNoChange: "Inget att rengöra.",
        urlCleanerCleaned: "URL rensad.",
        urlCleanerCopied: "Kopierade.",
        urlCleanerLocalNote: "Lokal. Inget nätverk.",

        homebrewName: "Hembryggt",
        homebrewEnableCaption: "Sök, installera och ta bort formler och fat.",
        homebrewMissingTitle: "Hembrygd hittades inte",
        homebrewMissingBody: "Vorssaint kan öppna Terminal med det officiella Homebrew-installationsprogrammet. Terminal visar stegen och ber om ditt lösenord om det behövs.",
        homebrewInstallHomebrew: "Installera Homebrew",
        homebrewInstallHomebrewCaption: "När terminalen är klar, kom tillbaka hit och klicka på Uppdatera.",
        homebrewInstallHomebrewOpened: "Installationsprogrammet har öppnats i Terminal.",
        homebrewShellSetupTitle: "Slutför terminalinställningen",
        homebrewShellSetupBody: "Homebrew är installerat, men Terminal kanske inte hittar bryggkommandot ännu. Vorssaint kan öppna Terminal med kommandot setup.",
        homebrewShellSetupButton: "Konfigurera terminal",
        homebrewShellSetupOpened: "Kommandot öppnat i Terminal. Gå sedan tillbaka hit och klicka på Uppdatera.",
        homebrewRefresh: "Uppdatera",
        homebrewCheckPackages: "Kontrollera paket",
        homebrewTrustTitle: "Tryck inte betrodd ännu",
        homebrewTrustCaption: "Homebrew ber nu om din bekräftelse innan du använder tredjepartskranar. Lita på %@ för att fortsätta.",
        homebrewTrustButton: "Lita på och fortsätt",
        homebrewSearchPlaceholder: "Sök paket",
        homebrewKeyboardHint: "Mellanslag eller Return stänger macOS-panelen. Använd sökknappen.",
        homebrewSearchButton: "Sök",
        homebrewSearchResults: "Resultat",
        homebrewInstalled: "Installerad",
        homebrewAll: "Alla",
        homebrewFormulas: "Formler",
        homebrewCasks: "Fat",
        homebrewNoPackages: "Inga paket hittades",
        homebrewDependencies: "Beroenden",
        homebrewGroupDependencies: "Gruppberoenden",
        homebrewOrphans: "Behövs inte längre",
        homebrewOrphansNote: "Installerade som beroenden, men inget installerat paket behöver dem längre.",
        homebrewDependencyUpdatesFormat: "Beroendeuppdateringar: %d",
        homebrewNoSelection: "Välj ett installerat paket eller sök efter ett nytt.",
        homebrewDetailsTitle: "Paketdetaljer",
        homebrewInstall: "Installera",
        homebrewUninstall: "Avinstallera",
        homebrewUpgrade: "Uppdatera",
        homebrewUpgradeAll: "Uppdatera alla",
        homebrewUpdateHomebrew: "Uppdatera Homebrew",
        homebrewAllPackages: "paket",
        homebrewOpenTerminal: "Öppna Terminal",
        homebrewCancelOperation: "Avboka",
        homebrewClearLog: "Rensa logg",
        homebrewLogTitle: "Logga",
        homebrewVersion: "Version",
        homebrewDescription: "Typ",
        homebrewHomepage: "Öppna webbplats",
        homebrewPopularity: "Popularitet",
        homebrewPopularityFormat: "%@ installeras om %@ dagar",
        homebrewInstalledBadge: "Installerad",
        homebrewNotInstalledBadge: "Ej installerad",
        homebrewUpdates: "Uppdateringar",
        homebrewUpdateAvailableBadge: "Uppdatering tillgänglig",
        homebrewLatestVersion: "Senast",
        homebrewConfirmInstallTitle: "Installera med Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew kommer att ladda ner och installera %@. Beroenden kan också installeras.",
        homebrewConfirmUninstallTitle: "Avinstallera med Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew kommer att avinstallera %@. Konfigurationsfiler kan finnas kvar på systemet.",
        homebrewConfirmUpgradeTitle: "Uppdatera med Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew kommer att ladda ner och tillämpa den senaste versionen av %@. Beroenden kan också uppdateras.",
        homebrewConfirmUpgradeAllTitle: "Uppdatera allt med Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew kommer att ladda ner och tillämpa de senaste versionerna för paket med tillgängliga uppdateringar. Beroenden kan också uppdateras.",
        homebrewConfirmUpdateHomebrewTitle: "Uppdatera Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew hämtar den senaste informationen och laddar sedan om dina paket.",
        homebrewTerminalFallback: "Denna operation kräver att Terminal frågar efter administratörslösenordet. Vorssaint fångar inte in lösenord.",
        homebrewLoading: "Belastning…",
        homebrewSearchEmpty: "Inga resultat",
        homebrewOperationInstallFormat: "Installerar %@",
        homebrewOperationUninstallFormat: "Avinstallerar %@",
        homebrewOperationUpgradeFormat: "Uppdaterar %@",
        homebrewOperationUpgradeAll: "Uppdaterar paket",
        homebrewOperationUpdateHomebrew: "Uppdaterar Homebrew",
        homebrewOperationInstalledFormat: "%@ installerat.",
        homebrewOperationUninstalledFormat: "%@ avinstallerad.",
        homebrewOperationUpgradedFormat: "%@ uppdaterad.",
        homebrewOperationUpgradedAll: "Paketen uppdaterade.",
        homebrewOperationUpdatedHomebrew: "Homebrew uppdaterad.",
        homebrewOperationFailedFormat: "Kunde inte avsluta %@.",
        homebrewOperationCancelled: "Åtgärden avbröts.",
        homebrewOperationPreparing: "Förbereder…",
        homebrewOperationDownloading: "Laddar ned filer…",
        homebrewOperationInstalling: "Installerar filer…",
        homebrewOperationUninstalling: "Tar bort filer…",
        homebrewOperationUpgrading: "Uppdaterar filer…",
        homebrewOperationFinalizing: "Avslutar…",
        homebrewOperationRefreshing: "Uppdaterar listan…",
        homebrewOperationTerminal: "Fortsätt i Terminal.",
        homebrewOperationElapsedFormat: "%@ har gått",
        homebrewOperationShowDetails: "Visa detaljer",
        homebrewOperationHideDetails: "Dölj detaljer",
        homebrewOperationTechnicalLog: "Tekniska detaljer",
        homebrewOperationProgressUnknown: "Homebrew har inte rapporterat någon procent ännu.",

        mediaName: "Media",
        mediaEnableCaption: "Komprimera videor, konvertera och bearbeta bilder, skapa GIF-filer och extrahera text lokalt.",
        mediaLocalNote: "Lokal. Inget nätverk.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Bild",
        mediaToolText: "Text",
        mediaSelectFile: "Välj fil",
        mediaDropHint: "Släpp en fil här eller klicka för att välja en.",
        mediaOutput: "Produktion",
        mediaOutputAutomatic: "Automatisk",
        mediaChooseOutput: "Destination",
        mediaStartVideo: "Komprimera video",
        mediaStartGIF: "Gör GIF",
        mediaStartImage: "Processbild",
        mediaStartConvertPDF: "Konvertera till PDF",
        mediaStartText: "Extrahera text",
        mediaCancel: "Avboka",
        mediaStartTime: "Starta",
        mediaEndTime: "Avsluta",
        mediaQuality: "Kompression",
        mediaCompressionLow: "Låg",
        mediaCompressionMedium: "Medium",
        mediaCompressionHigh: "Hög",
        mediaCompressionLowDescription: "Hög kvalitet, stor filstorlek",
        mediaCompressionMediumDescription: "Balanserad kvalitet och filstorlek",
        mediaCompressionHighDescription: "Låg kvalitet, liten filstorlek",
        mediaMaxSize: "Storlek",
        mediaSizingResolution: "Upplösning",
        mediaSizingFileSize: "Fil-storlek",
        mediaTargetSize: "Målstorlek",
        mediaTargetSizeHint: "Upplösningen anpassar sig för att hålla sig under gränsen.",
        mediaErrorTargetTooSmall: "Målstorleken är för liten för det här klippet. Klipp den eller höj gränsen.",
        mediaMegabytesSuffix: "MB",
        mediaWidth: "Bredd",
        mediaFPS: "FPS",
        mediaKeepAudio: "Behåll ljud",
        mediaCodec: "Codec",
        mediaFormat: "Formatera",
        mediaStripMetadata: "Ta bort metadata",
        mediaLoopGIF: "Slinga GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Exakt",
        mediaOCRFast: "Snabb",
        mediaLanguageCorrection: "Språkkorrigering",
        mediaTextOutputNote: "Extraherad text kan kopieras och sparas som TXT.",
        mediaRunning: "Bearbetning",
        mediaCompleted: "Gjort",
        mediaCancelled: "Avbruten.",
        mediaOpenInFinder: "Visa",
        mediaCopyText: "Kopiera text",
        mediaRunAgain: "Kör igen",
        mediaEmptyText: "Ingen text hittades.",
        mediaResultSavedFormat: "Sparad som %@",
        mediaResultSizeFormat: "%@ till %@",
        mediaResultGrewCaption: "Den konverterade filen blev större än originalet.",
        mediaErrorNoFile: "Välj en fil först.",
        mediaErrorNoVideo: "Den här filen har inget videospår.",
        mediaErrorSameOutput: "Välj en annan destination än originalfilen.",
        mediaErrorUnsupported: "Formatet stöds inte av macOS.",

        shelfName: "Hylla",
        shelfEnable: "Tillfälligt område för att dra filer",
        shelfEnableCaption: "En flytande plats för att samla in filer, bilder och text och sedan dra dem någonstans senare.",
        shelfHowTitle: "Hur man använder",
        shelfStep1: "Öppna den med genvägen eller genom att skaka musen under ett drag.",
        shelfStep2: "Släpp filer, bilder, länkar eller text på den för att hålla dem.",
        shelfStep3: "Dra varje objekt tillbaka ut till valfri app när du behöver det.",
        shelfShakeToggle: "Öppna genom att skaka musen medan du drar",
        shelfShakeCaption: "Skaka pekaren snabbt medan du håller ett objekt för att framkalla det nära markören.",
        shelfDropZoneToggle: "Behåll släpade filer i menyraden",
        shelfDropZoneCaption: "Medan du drar en fil visas hyllan under menyradens ikon. Vad du än tappar förvaras där, i en knapp du krymper och öppnar med ett klick som försvinner när hyllan är tom.",
        shelfDropZoneCaptionTopCenter: "Medan du drar en fil visas hyllan som ett märke längst upp i mitten av skärmen. Vad du än tappar förvaras där, i ett märke öppnar du med ett klick som försvinner när hyllan är tom.",
        shelfDropZoneLabel: "Släpp här",
        shelfDockPlacement: "Placera",
        shelfDockMenuBar: "Under menyradens ikon",
        shelfDockTopCenter: "Övre mitten av skärmen",
        shelfDockIslandNote: "Dynamic Island behåller den övre mitten medan den är på.",
        shelfCollapse: "Kollapsa",
        shelfBehaviorTitle: "Efter användning",
        shelfCloseAfterDrop: "Stäng efter att ha hamnat i en annan app",
        shelfCloseAfterDropCaption: "Stänger hyllan när destinationen accepterar föremålen. Stiftet i panelen håller den öppen.",
        shelfRemoveAfterDrop: "Ta bort föremål efter att du tappat dem",
        shelfRemoveAfterDropCaption: "Föremål som accepteras av en annan app lämnar hyllan. Stäng av detta för att behålla en kopia där. Fästa föremål stannar alltid.",
        shelfExclusionsTitle: "Automatiska undantag",
        shelfExclusionsEmpty: "Inga appar har lagts till.",
        shelfExclusionsCaption: "Skaka och menyradens släppzon förblir avstängd för drag som startas i dessa appar. Genvägen och Öppna fungerar nu fortfarande.",
        shelfPin: "Håll öppet",
        shelfUnpin: "Tillåt stängning efter användning",
        extraBrightnessName: "Extra ljusstyrka",
        extraBrightnessCaption: "Använder skärmens HDR-höjd för att passera den maximala ljusstyrkan. Använder mer batteri och Mac kan bli varm.",
        extraBrightnessLevelLabel: "Intensitet",
        extraBrightnessUnsupported: "Endast tillgängligt på XDR-skärmar, som de på 14 och 16 tums MacBook Pro.",
        shelfHotkeyLabel: "Genväg",
        shelfOpenNow: "Öppna nu",
        shelfNoPermission: "Kräver inga behörigheter.",
        shelfMenuItem: "Öppen hylla",
        shelfTitle: "Hylla",
        shelfEmpty: "Dra objekt hit",
        shelfClearAll: "Rensa alla",
        shelfRemoveSelected: "Ta bort markerade",
        shelfSelectedFormat: "%d har valts",
        shelfHint: "Klicka för att välja. Dra ut för att använda eller högerklicka för fler åtgärder.",
        shelfItemImage: "Bild",
        shelfTooltipItemsFormat: "%d objekt",
        shelfTooltipItemsFew: "%d objekt",
        shelfTooltipImageSingular: "%d bild",
        shelfTooltipImageFew: "%d bilder",
        shelfTooltipImagePlural: "%d bilder",
        shelfTooltipFileSingular: "%d fil",
        shelfTooltipFileFew: "%d filer",
        shelfTooltipFilePlural: "%d filer",
        shelfTooltipNoteSingular: "%d anteckning",
        shelfTooltipNoteFew: "%d anteckningar",
        shelfTooltipNotePlural: "%d anteckningar",
        shelfTooltipLinkSingular: "%d länk",
        shelfTooltipLinkFew: "%d länkar",
        shelfTooltipLinkPlural: "%d länkar",
        shelfActionOpen: "Öppna",
        shelfActionOpenWith: "Öppna med",
        shelfActionShare: "Dela",
        shelfActionPin: "Stift",
        shelfActionUnpin: "Lossa",

        breakdownMeasuring: "Mätning…",

        mixerSection: "Volymmixer",
        mixerEmpty: "Appar som använder ljud visas här",
        mixerUnavailable: "Tillgänglig på macOS 14.4 och senare",
        mixerPermissionBody: "För att justera volymen per app, tillåt \"Skärm- och systemljudinspelning\" i Systeminställningar. Ljud spelas aldrig in.",
        mixerResetTooltip: "Återställ till 100 %",
        mixerOutputDefault: "Standard",
        mixerOutputCurrent: "nuvarande",
        mixerOutputUnavailable: "Utdata inte tillgänglig",
        mixerOutputFallback: "Använder standard tills den här enheten kommer tillbaka.",
        mixerBypassedCaption: "Denna app hanterar sitt eget ljud.",
        mixerOutputTooltip: "Välj utgång",
        mixerAirPlayChooseSpeaker: "Välj AirPlay-högtalare...",
        mixerSystemOutputTitle: "Produktion",
        mixerSystemOutputNoDevices: "Inga utgångar hittades",
        mixerSystemOutputTooltip: "Välj systemutgång",
        mixerSystemOutputErrorFormat: "Kunde inte byta: %@",
        mixerLowerOnHeadphonesDisconnect: "Sänk volymen när hörlurarna kopplas bort",
        mixerLowerOnHeadphonesDisconnectCaption: "Justerar utsignalen när trådbundna eller Bluetooth-hörlurar kopplas bort.",
        mixerHeadphonesDisconnectVolume: "Volym efter frånkoppling",
        preciseVolumeRollerEnable: "Använd finare volymsteg",
        preciseVolumeRollerCaption: "Förvandlar volymhjul och nycklar till mindre systemvolymsteg.",
        preciseVolumeRollerTapFailed: "Kunde inte lyssna efter volymknappar.",
        soundOutputSwitcherTitle: "Utgångsomkopplare",
        soundOutputSwitcherEnable: "Växla utgångar med genväg",
        soundOutputSwitcherCaption: "Välj utgångar och använd genvägen för att gå till nästa tillgängliga.",
        soundOutputSwitcherDevices: "Utgångar i cykel",
        soundOutputSwitcherNoAvailableSelection: "Välj minst en tillgänglig utgång.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Inga mikrofoner hittades",
        mixerInputUnavailable: "Mikrofonen är inte tillgänglig",
        mixerInputFallback: "Använder standard tills denna mikrofon kommer tillbaka.",
        mixerInputTooltip: "Välj mikrofon",
        mixerInputErrorFormat: "Kunde inte byta: %@",
        mixerVisibleApps: "Appar i listan",
        mixerAllShown: "Alla",
        mixerHiddenCountLabel: "Dold",
        mixerHideFromList: "Göm från listan",
        audioPrioritySection: "Ljudprioritet",
        audioPriorityOutputEnable: "Växla automatiskt till den högsta prioriterade utgången",
        audioPriorityInputEnable: "Växla automatiskt till den högst prioriterade mikrofonen",
        audioPriorityOutputList: "Utgångsprioritet",
        audioPriorityInputList: "Mikrofonprioritet",
        audioPriorityMoveUp: "Flytta upp",
        audioPriorityMoveDown: "Flytta ner",
        audioPriorityUnavailable: "Inte tillgänglig",
        audioPriorityCurrent: "Nuvarande",
        audioPriorityCaption: "Enheter väljs i prioritetsordning. När en enhet med högre prioritet ansluter blir den aktiv. När den aktiva kopplar ur tar nästa tillgängliga över.",

        updatesSection: "Uppdateringar",
        autoCheckToggle: "Sök efter uppdateringar automatiskt",
        includeBetaUpdatesToggle: "Ta emot betauppdateringar",
        includeBetaUpdatesCaption: "Betaversioner inkluderar funktioner under utveckling och kan innehålla buggar eller ofullständigt beteende.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Kolla nu",
        updateChecking: "Kontroll…",
        updateUpToDate: "Du har den senaste versionen.",
        updateAvailablePrefix: "Uppdatering tillgänglig:",
        updateInstallButton: "Ladda ner och installera",
        updateDownloading: "Laddar ned uppdatering...",
        updateInstalling: "Installerar och startar om...",
        updateFailedPrefix: "Kunde inte kontrollera:",
        updateLastChecked: "Senast kontrollerad:",
        updateNotifyTitle: "Vorssaint uppdatering",
        updateInstallFailedBody: "Uppdateringen laddades ner men kunde inte tillämpas. Ladda ner den senaste versionen från GitHub-versionssidan och dra appen över den aktuella.",
        updateNeedsApplicationsTitle: "Flytta Vorssaint till applikationer",
        updateNeedsApplicationsBody: "Appen körs från en plats som inte kan uppdateras, till exempel diskavbildningen eller en tillfällig systemplats. Dra Vorssaint till mappen Applications, öppna den därifrån och försök igen.",
        menuCheckUpdates: "Sök efter uppdateringar...",

        permissionRequired: "Tillstånd krävs",
        permissionAccessibility: "Tillgänglighet",
        permissionScreenRecording: "Skärminspelning",
        permissionGranted: "Beviljas",
        permissionMissing: "Inte beviljat",
        permissionOpenSettings: "Öppna Systeminställningar...",
        permissionRequest: "Bevilja åtkomst",
        permissionRestartNote: "macOS kan begära att få öppna appen igen efter att ha beviljats.",
        secureInputTitle: "Säker ingång är på",
        secureInputHeldFormat: "%@ håller den, så Vorssaint kan inte skriva åt dig. Stäng lösenordsfältet eller avsluta det för att släppa det.",
        secureInputUnattributed: "Ingen löpande app gör anspråk på det. Logga ut och in igen för att rensa det.",
        secureInputUnidentified: "Appen som innehöll den kunde inte identifieras, så Vorssaint kan inte skriva åt dig.",
        secureInputRevealFormat: "Visa %@",

        aboutDescription: "En verktygshubb för din Mac.\nEnergi, systemmonitor, rullning och en fönsterväxlare, direkt i menyraden.",
        versionPrefix: "Version",
        reviewIntro: "Granska introduktionen",
        reviewHighlights: "Granska höjdpunkter",
        viewOnGitHub: "Visa på GitHub",

        obContinue: "Fortsätt",
        obBack: "Tillbaka",
        obSkipStep: "Hoppa över detta steg",
        obStart: "Öppna Vorssaint",
        obStepWelcomeTitle: "Välkommen till Vorssaint",
        obStepWelcomeBody: "Ett diskret menyradsverktyg som gör vardagens macOS mer praktiskt.",
        obWelcomeBullet1Title: "Energi under kontroll",
        obWelcomeBullet1Body: "Håll Mac-datorn vaken så länge du vill, även med locket stängt.",
        obWelcomeBullet2Title: "En tydlig bild av systemet",
        obWelcomeBullet2Body: "CPU, GPU och batteritemperaturer, hårdvaruanvändning och minnestryck i realtid.",
        obWelcomeBullet3Title: "Mus och fönster, på ditt sätt",
        obWelcomeBullet3Body: "Omvänd musrullning och en fönsterväxlare med miniatyrer.",
        obLanguageLabel: "Språk",
        obStepAccessibilityTitle: "Tillgänglighet",
        obStepAccessibilityBody: "Behövs för att invertera musrullning och för att fönsterväxlaren ska svara på tangentbordet.",
        obAccessibilityWhy: "Appen tittar bara på mushjulet och växlingsgenvägen. Ingenting registreras eller skickas någonstans.",
        obStepRecordingTitle: "Skärminspelning",
        obStepRecordingBody: "Låter växlaren visa riktiga fönsterminiatyrer istället för endast ikoner.",
        obRecordingWhy: "Miniatyrer genereras i farten, stannar kvar i minnet och lämnar aldrig din Mac. Utan den fungerar switchern fortfarande med ikoner.",
        obStepMonitorTitle: "Systemövervakare",
        obStepMonitorBody: "Panelen visar CPU, GPU och batteritemperaturer, hårdvaruanvändning och minnestryck.",
        obMonitorNoPermission: "Inget tillstånd behövs. Sensorer läses direkt från systemet.",
        obStepOptionalTitle: "Valfria funktioner",
        obStepOptionalBody: "Slå på det du vill använda nu. Allt kan ändras senare i Inställningar.",
        obStepStatusTitle: "Kontroll",
        obStepStatusBody: "Se till att allt är klart för de funktioner du vill ha.",
        obStatusRecheck: "Kontrollera igen",
        obStepDoneTitle: "Allt klart!",
        obStepDoneBody: "Vorssaint tar redan hand om din Mac.",
        obDoneHint: "Leta efter det svarta hålet i menyraden, längst upp till höger på skärmen.",
        obWhatsNewTitle: "Vad är nytt i den här versionen",
        obWhatsNewFallback: "Den här uppdateringen innehåller de senaste korrigeringarna och förbättringarna.",
        obLanguageUpdateTitle: "Nu på ditt språk",
        obLanguageUpdateBody: "Vorssaint talar nu flera språk. Välj den du vill använda; du kan ändra det när som helst i Inställningar.",
        obPurposeTitle: "Vad tog dig hit?",
        obPurposeBody: "Välj en färdig installation eller välj exakt vad du vill använda.",
        obPurposeSkip: "Du kan lägga till eller ta bort funktioner senare i Inställningar.",

        tabMonitor: "Övervaka",
        monitorMenuBarSection: "I menyraden",
        monitorMenuBarCaption: "Välj vad som visas bredvid ikonen i menyraden.",
        monitorCombineTemperatures: "Kombinera användning och temperatur",
        monitorCombineTemperaturesCaption: "När användning och temperatur för samma objekt är aktiverade, visa dem i ett block.",
        monitorSeparateMenuBarMetrics: "Separera mätvärden i sina egna objekt",
        monitorSeparateMenuBarMetricsCaption: "Separerar aktiva block i menyraden och håller ihop användning och temperatur när skördetröskan är på.",
        monitorNetworkUploadFirst: "Ladda upp nedladdning ovan",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Minne",
        monitorShowNetwork: "Nätverk",
        monitorShowPowerLabel: "Driva",
        monitorIntervalLabel: "Uppdatera varje",
        monitorInterval1: "1 sekund",
        monitorInterval2: "2 sekunder",
        monitorInterval5: "5 sekunder",
        monitorPanelSection: "I panelen",
        panelNavigationMode: "Navigera panelen efter sektioner",
        panelNavigationCaption: "Visar ett avsnitt i taget. Välj Lista för att se allt i en kontinuerlig rullning.",
        panelFooterSections: "Avsnitt",
        panelFooterList: "Lista",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Du kan stöta på några buggar.",

        networkSection: "Nätverk",
        networkIPAddresses: "IP-adresser",
        networkLocalIP: "Lokal IPv4",
        networkDownload: "Ladda ner",
        networkUpload: "Ladda upp",
        networkThisSession: "Denna session",
        networkMeasuring: "Mätning…",
        networkApps: "Appar som använder nätverk",
        networkAppsIdle: "Inga appar använder nätverk nu",

        diskSection: "Diskar",
        diskUsed: "begagnad",
        diskFree: "gratis",
        diskMenuBarStyleLabel: "Diskdisplay",
        diskMenuBarUsedPercentage: "Använt procent",
        diskMenuBarAvailableSpace: "Tillgängligt utrymme",
        diskMenuBarUsedSpace: "Använd utrymme",
        diskAvailable: "tillgänglig",
        diskPurgeable: "rensningsbar",
        diskInternal: "Inre",
        diskExternal: "Extern",
        diskSelect: "Välj disk",
        diskRead: "Läsa",
        diskWrite: "Skriva",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART är inte tillgängligt för den här disken",
        diskTotalRead: "Totalt läst",
        diskTotalWritten: "Totalt skrivet",
        diskTemperature: "Temperatur",
        diskHealth: "Hälsa",
        diskPowerCycles: "Power cykler",
        diskPowerOnHours: "Ström på timmar",
        diskUnsafeShutdowns: "Osäkra avstängningar",
        diskMediaErrors: "Mediafel",
        diskEject: "Mata ut",
        diskEjectAll: "Ta bort alla",
        diskEjecting: "Matar ut...",
        diskReadyToRemove: "Klar att ta bort",
        diskEjectFailed: "Det gick inte att mata ut",
        diskProtectionCaption: "Mata ut innan du drar ur kontakten.",
        diskNoExternal: "Ingen extern disk redo att matas ut.",
        diskOpenInFinder: "Öppna",
        diskStorageSettings: "Lagring",
        diskNoDisks: "Inga monterade diskar hittades.",

        powerSection: "Driva",
        powerSystem: "System",
        powerAdapter: "Adapter",
        powerBattery: "Batteri",
        powerCharging: "Laddar",
        powerOnBattery: "På batteri",
        powerPluggedIn: "Inkopplad",
        powerUnavailable: "Effektmätningar är inte tillgängliga på denna Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU temperatur",
        monitorShowGPUTemperature: "GPU temperatur",
        monitorShowBatteryTemperature: "Batteritemperatur",
        monitorShowPeripheralBattery: "Perifert batteri",
        peripheralBatteryNoDevices: "Inga enheter hittades",
        monitorGraphsSection: "Grafer",

        updateBannerTitle: "Uppdatering tillgänglig",
        updateBannerAction: "Uppdatera",
        obStepMenuBarTitle: "Mätvärden i menyraden",
        obStepMenuBarBody: "Välj vad som ska visas bredvid ikonen. Förhandsvisningen ovan uppdateras live.",
        obStepMenuBarNote: "Nytt: Nätverks- och Powerblock och grafer i panelen. Finjustera allt senare i Inställningar › Monitor.",
        monitorMenuBarPresetLabel: "Stil",
        menuBarPresetReadable: "Läsbar",
        menuBarPresetDense: "Tät",
        menuBarSpacingLabel: "Menyradens mellanrum",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Kompakt",
        menuBarHideIconToggle: "Dölj appikonen medan mätvärden visas",
        menuBarHideIconCaption: "Ikonen återkommer av sig själv när mätvärden lämnar fältet och när det finns något att signalera (en uppdatering klar, \"Keep awake\" igång eller mikrofonen avstängd).",
        monitorLabelStyleLabel: "Etiketter",
        menuBarLabelStyleCompact: "Kompakt",
        menuBarLabelStyleClassic: "Klassisk",
        monitorMemoryStyleLabel: "Visa minne som",
        monitorMemoryPressureDot: "Tryckpunkt",
        memoryStyleDot: "Punkt",
        memoryStylePercent: "%",
        memoryStyleBoth: "Både",
        systemUptime: "Upp för",
        batteryCharge: "Avgift",
        powerHealth: "Batterihälsa",
        powerCycles: "Cyklar",
        speedTestRun: "Hastighetstest",
        speedTestAgain: "Testa igen",
        speedTestLatency: "Latens",
        speedTestTesting: "Testning…",
        speedTestFailed: "Testet misslyckades",

        monitorShowInPanel: "Visa i panelen",
        disclosureExpanded: "Utökad",
        disclosureCollapsed: "Kollapsade",
        panelHideItem: "Dölj från panelen",
        panelShowItem: "Visa i panelen",
        panelHiddenItem: "Dold",
        monitorItemUptime: "Upptid",
        monitorItemNetSpeed: "Live hastighet",
        monitorItemNetTotals: "Sessionssummor",
        monitorItemNetTest: "Hastighetstest",
        monitorItemDiskUsage: "Diskanvändning",
        monitorItemDiskActivity: "Liveaktivitet",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Yttre skydd",
        monitorItemDiskTools: "Verktyg",
        monitorPanelConfigHint: "Öppna ett block för att välja vad det visar.",
        monitorOrderHint: "Dra för att ändra ordning på panelsektionerna och använd ögat för att visa eller dölja var och en.",
        obStepPanelTitle: "Vad finns i panelen",
        obStepPanelBody: "Öppna varje block och välj exakt vad som visas när du klickar på ikonen.",
        obStepPanelNavigationTitle: "Sektionsbaserad panel",
        obStepPanelNavigationBody: "Panelen kan nu visa ett avsnitt i taget. Du kan växla mellan sektioner och lista i Inställningar.",

        cleaningMenuItem: "Rengöringsläge",
        utilitiesSection: "Verktyg",
        quickControlsSection: "Kontroller",
        panelCategoryWindows: "Windows",
        panelCategoryInput: "Mus och tangentbord",
        panelCategoryFiles: "Filer",
        windowMaximizeName: "Maximera fönster",
        windowMaximizeCaption: "Den gröna knappen maximeras utan att skapa ytterligare ett utrymme.",
        windowMaximizeActiveNow: "Grön knappöverstyrning aktiv",
        windowMaximizeNeedsAccessibility: "Behöver tillgänglighet för att arbeta.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrera dubbletter av nycklar",
        keyDebounceCaption: "Filtrerar mycket snabba dubbletter av tangenttryckningar.",
        keyDebounceActiveNow: "Filter aktivt",
        keyDebounceGlobalWindow: "Globalt fönster",
        keyDebouncePerKeySection: "Specifika nycklar",
        keyDebouncePerKeyCaption: "Värden per nyckel åsidosätter det globala fönstret. Använd 0 ms för att sluta filtrera en nyckel.",
        keyDebounceKeyLabel: "Nyckel",
        keyDebounceWindowLabel: "Fönster",
        keyDebounceAddKey: "Lägg till nyckel",
        keyDebounceNoOverrides: "Inga specifika nycklar konfigurerade.",
        keyDebounceRemoveKey: "Ta bort nyckeln",
        cleaningPanelCaption: "Låser tangentbordet så att du kan rengöra säkert.",
        cleaningOverlayTitle: "Tangentbordet låst för rengöring",
        cleaningOverlaySubtitle: "Tryck på Escape 5 gånger för att låsa upp",
        cleaningOverlayUnlock: "Låsa upp",
        cleaningOverlayMouseHint: "Din mus och styrplatta fungerar fortfarande",
        cleaningKeepScreenVisibleToggle: "Håll skärmen synlig",
        cleaningKeepScreenVisibleCaption: "Visar en diskret indikator i hörnet av skärmen istället för att mörklägga innehåll.",
        cleaningStartNow: "Lås tangentbordet nu",
        cleaningNeedsAxTitle: "Tillgänglighet behövs",
        cleaningNeedsAxBody: "För att låsa tangentbordet på ett säkert sätt behöver Vorssaint tillgänglighetstillstånd. Bevilja det i Systeminställningar och försök igen.",

        tabSupport: "Stöd",
        shortcutsPageCaption: "Redigera alla globala genvägar från funktionerna som är installerade på denna Mac. Inaktiva genvägar förblir sparade men körs inte.",
        shortcutsPageTitle: "Kortkommandon",
        settingsSearchPlaceholder: "Sökinställningar",
        donateHeading: "Hjälp Vorssaint att fortsätta växa",
        donateMessage: "Vorssaint är fri, oberoende och byggd på min fritid. Om du skulle vilja bidra ekonomiskt hjälper Köp mig en kaffe mig direkt att fortsätta utvecklingen framåt.",
        donateButton: "Stöd via Buy Me a Coffee",
        donateThanks: "Tack för att du är här. 🖤",
        supportIntroTitle: "Hjälp Vorssaint att fortsätta växa",
        supportIntroMessage: "Om du vill stödja utvecklingen ekonomiskt är Buy Me a Coffee det enda stället att göra det.",
        supportIntroStarButton: "Stjärna Vorssaint på GitHub",
        supportIntroStarMessage: "Ekonomiskt stöd förväntas aldrig. En stjärna på GitHub hjälper fler att upptäcka Vorssaint och gör en verklig skillnad för dess utveckling.",
        supportIntroCoffeeButton: "Stöd via Buy Me a Coffee",
        supportIntroLaterButton: "Inte nu",
        supportIntroDoneButton: "Gjort",
        discordIntroTitle: "Vorssaint Discord-communityt har precis börjat",
        discordIntroMessage: "Vorssaint-samhället är nytt och byggs fortfarande. Gå med tidigt för att träffa andra användare och hjälpa till att bygga ett välkomnande utrymme runt appen.",
        discordIntroJoinButton: "Gå med i Discord-communityt",
        communityIntroTitle: "Se det före alla andra",
        communityIntroMessage: "Personer som redan följt mig på X såg flera ändringar i den här uppdateringen före någon annan. Jag lägger upp förhandstittar på vad som kommer och visar hur det fungerar, så att du redan kan grunderna innan uppdateringen skickas. Följ med och se vad som kommer härnäst!",
        communityIntroFollowButton: "Följ @vorssaint på X",
        homebrewOfficialIntroTitle: "Nu i den officiella Homebrew-katalogen",
        homebrewOfficialIntroMessage: "Vorssaint kan nu installeras direkt från den officiella Homebrew-katalogen.",
        homebrewOfficialIntroInstallLabel: "Ny installation",
        homebrewOfficialIntroMigrationTitle: "Använd den gamla kranen?",
        homebrewOfficialIntroMigrationMessage: "Ta bort kranen en gång. Appen och dina inställningar förblir på plats.",
        homebrewOfficialIntroCopyButton: "Kopiera kommando",
        updateShowcaseTitle: "Vad är nytt i 3.1.4",
        updateShowcaseMessage: "Ta en snabb titt på de viktigaste förbättringarna i den här uppdateringen.",
        updateShowcaseUnavailable: "Videon kunde inte laddas just nu. Du kan fortfarande fortsätta.",
        updateShowcaseRestart: "Starta om",
        showMenuBarIcon: "Visa menyradsikon",
        menuBarIconStillHiddenTitle: "Ikonen är fortfarande dold",
        menuBarIconStillHiddenBody: "Ikonen byggdes om, men macOS gav den inte en synlig plats. Menyraden är förmodligen slut: ta bort några menyradsikoner (eller stäng appar med långa menyer) och försök igen.",
        menuBarIconManagerHintFormat: "%@ är öppen och kan ha kvar ikonen i sin dolda sektion. Leta efter Vorssaint där, eller ställ in %@ för att alltid visa Vorssaint.",
        menuBarIconDisallowedBody: "macOS håller Vorssaint borta från menyraden. Öppna Systeminställningar > Menyrad, hitta Vorssaint i applistan och aktivera \"Tillåt i menyraden\". Ikonen visas så snart strömbrytaren är på.",
        shortcutRecording: "Tryck på den nya genvägen",
        shortcutReset: "Återställa",
        shortcutNone: "None",
        shortcutClear: "Remove shortcut",
        shortcutInvalid: "Use at least Control, Option or Command with a key.",
        shortcutPressKeys: "Press keys",
        shortcutEscapeHint: "Escape cancels.",
        shortcutDeleteHint: "Ta bort rensar.",
        shortcutNotCaptured: "Ingenting fångades. macOS eller en annan app använder redan den kombinationen. Prova en annan.",
        shortcutConflictFormat: "Den här genvägen används redan av %@.",
        shortcutTakeOverOffer: "macOS använder %@ för en av sina egna genvägar.",
        shortcutTakeOverAction: "Take over while Vorssaint runs",
        shortcutTakeOverCaption: "macOS gets the key back whenever Vorssaint is not running or this feature is off.",
        shortcutTakeOverDismiss: "Don’t take over",
        shortcutUnavailable: "macOS avvisade denna genväg. Välj en annan.",
        shelfShortcutToggle: "Hylla genväg",
        switcherUsageHintFormat: "Hold %@ to navigate; release to activate the window. Shift or ← goes back; W closes the window; Q quits the app; Esc cancels.",
        musicBlockSection: "Media keys",
        musicBlockTitle: "Stoppa musik från att öppna av sig själv",
        musicBlockCaption: "Blocks the music app opening after a detected media key. Requires Accessibility access. Headphone commands without a detected key are left alone.",
        musicBlockUnavailable: "This protection is unavailable right now. Turn it off and on to try again.",
        musicBlockReplacementLabel: "Open instead",
        musicBlockReplacementNone: "None",
        musicBlockReplacementBlocked: "Music and iTunes are the apps being blocked, so they can’t open instead. Choose another app.",
        musicBlockChooseApp: "Välj app...",
        musicBlockPlayReplacement: "Play after opening replacement",
        cleanerName: "Cleaner",
        cleanerIntroTitle: "Clean up your Mac",
        cleanerIntroCaption: "Scans for leftovers from uninstalled apps, caches, logs and the Trash. You review everything first and removed items go to the Trash.",
        cleanerScan: "Scan",
        cleanerScanning: "Scanning…",
        cleanerCleaning: "Cleaning…",
        cleanerCatLeftovers: "Leftovers from uninstalled apps",
        cleanerCatLoginItems: "Orphaned startup items",
        cleanerCatCaches: "Cacher",
        cleanerCatLogs: "Loggar",
        cleanerCatDeveloper: "Developer junk",
        cleanerCatTrash: "Trash",
        cleanerLeftoversNote: "Found by analysis and left unchecked. Check the path before ticking.",
        cleanerLoginItemsNote: "The entry under Login Items disappears after restarting the Mac.",
        cleanerTrashNote: "Emptying the Trash is permanent.",
        cleanerCatDeviceBackups: "iPhone backups",
        cleanerDeviceBackupsCaption: "Old iPhone and iPad backups take a big slice of the storage macOS calls Other. Remove only the ones you no longer need; a new backup is made when you plug the device in again.",
        cleanerCatScreenshots: "Forgotten screenshots",
        cleanerScreenshotsCaptionFormat: "Screenshots you have not opened in %d days that still have the name and folder macOS gave them. Ones you renamed or moved never show up here.",
        cleanerScreenshotsSettingCaption: "The scan lists the screenshots you have not opened for this long, unchecked, with their total size.",
        cleanerScreenshotsAfterFormat: "After %d days",
        cleanerNothingFound: "Nothing to clean. Your Mac is tidy.",
        cleanerClean: "Clean",
        cleanerDoneNote: "Items went to the Trash and can be recovered from there.",
        cleanerAgain: "Scan again",
        cleanerRevealInFinder: "Reveal in Finder",
        cleanerPanelCaption: "App leftovers, caches and logs",
        cleanerSafeSection: "Safe cleanup",
        cleanerOptionalSection: "Optional, review first",
        cleanerCatOtherCaches: "Other caches",
        cleanerCachesCaption: "Temporary files apps rebuild on their own.",
        cleanerLogsCaption: "Old diagnostic logs.",
        cleanerDeveloperCaption: "Xcode build and simulator leftovers.",
        cleanerLoginItemsCaption: "Startup entries left by apps that no longer exist.",
        cleanerLeftoversCaption: "Files left behind by apps you uninstalled.",
        cleanerOtherCachesCaption: "Safe to remove, nothing breaks. Apps may open slower once and downloaded content, like offline music, downloads again.",
        cleanerCleanSizeFormat: "Clean %@",
        cleanerScheduleTitle: "Automatic cleanup",
        cleanerScheduleOff: "Av",
        cleanerScheduleDaily: "Daily",
        cleanerScheduleWeekly: "Weekly",
        cleanerScheduleCaption: "Cleans only the safe part on its own at the chosen time and sends everything to the Trash.",
        cleanerScheduleLastFormat: "The last automatic cleanup freed %@.",
        cleanerAutoNotificationFormat: "%@ freed and sent to the Trash.",
        cleanerScheduleNextFormat: "Next cleanup %@.",
        cleanerScheduleRanFormat: "Last automatic cleanup %@.",
        cleanerScheduleNotifyToggle: "Notify when done",
        cleanerNotifDenied: "Vorssaint notifications are turned off in the system.",
        cleanerNotifOpenSettings: "Open Notification Settings…",
        launchAtLoginNeedsApplications: "The app is running from a place that cannot open at login. Drag Vorssaint to the Applications folder, open it from there and turn this on again.",
        launchAtLoginNeedsApproval: "The login item is registered, but macOS still needs your approval. In System Settings, allow Vorssaint to open at login and to run in the background.",
        ocrRemoveLineBreaksToggle: "Remove line breaks",
        ocrRemoveLineBreaksCaption: "Removes line breaks so copied text pastes as one paragraph.",
        ocrQRToggle: "Read QR codes",
        ocrQRCaption: "If the area has a QR code, its content is shown to copy or open.",
        ocrQRCopied: "QR code copied",
        qrResultTitle: "QR code",
        qrResultCopy: "Kopiera",
        qrResultOpen: "Open link",
        highlightsTitle: "New in this update",
        highlightsTitleClipboardRedesign: "Redesigned clipboard",
        highlightsTitleWindowLayout: "Window Layout",
        highlightsTitleQuitProtection: "Quit and close protection",
        highlightsTitleRecorderBlur: "Recording privacy blur",
        highlightsCaptionDockPreview: "Dock Preview now works with Dock magnification turned on",
        highlightsCaptionScreenshot: "The screenshot tool gained a pixel loupe and QR code reading",
        highlightsCaptionSnippetLibrary: "A searchable snippet menu types any snippet right at your cursor",
        highlightsCaptionCapturePalette: "One shortcut now opens a floating palette for screenshots, recordings, screen text and colors with nearby controls.",
        highlightsCaptionClipboardRedesign: "Clipboard history now opens as a compact palette with uncluttered rows and an on-demand preview for reading or editing the full item.",
        highlightsCaptionWindowLayout: "Position windows with the directional ring using a shortcut and pointer, or drag to screen edges to snap with custom gaps.",
        highlightsCaptionQuitProtection: "Avoid quitting apps or closing windows by accident with a hold, a double press or an extra modifier, customizable per app.",
        highlightsCaptionRecorderBlur: "Hide private details, passwords and sensitive areas anywhere across your recorded video before sharing or exporting.",
        highlightsConfigure: "Set up",
        highlightsTry: "Try it",
        highlightsSeeAll: "See all changes",
        switcherCurrentSpaceOnly: "Show only the current desktop",
        switcherCurrentSpaceOnlyCaption: "Lists only windows from the desktop you are on. Picking a window never moves you to another desktop.",
        shelfFileMissing: "The file no longer exists",
        previewSizeSmall: "Small",
        mixerSoundEffectsOutputTitle: "System sounds",
        mixerSoundEffectsOutputTooltip: "Choose where alerts and sound effects play",
        monitorOpenActivityMonitor: "Open Activity Monitor",
        dockClickHide: "Click the Dock icon to hide the app",
        dockClickHideCaption: "The active app hides when you click its Dock icon. Click again to bring it back.",
        monitorMemoryMetricLabel: "Measure memory as",
        memoryMetricUsed: "Memory Used",
        memoryMetricApp: "App Memory",
        keepAwakeRightClickToggle: "Right-click the menu bar icon to toggle Keep Awake",
        keepAwakeRightClickToggleCaption: "Replaces the right-click context menu.",
        urlCleanerRulesTitle: "Cleaning rules",
        urlCleanerRulesCaption: "A site attaches these parameters to its own share links to track where the link came from. Switched on, a name is removed when a link is cleaned; switched off, it stays. Names you add can be deleted.",
        urlCleanerRulesCoverageCaption: "The list covers a site’s different share paths (the web page, the app, a live room), which is why it is long; a real link usually carries only two to four of them.",
        urlCleanerRulesAllSites: "All sites",
        urlCleanerRulesCountSingular: "1 parameter",
        urlCleanerRulesCountPluralFormat: "%d parameters",
        urlCleanerRulesAddSite: "Add a site",
        urlCleanerRulesParameterPlaceholder: "Parameter name",
        urlCleanerRulesMatchCaption: "Write the name to the left of the = , like utm_source. A name that matches takes that one parameter out of the link and leaves the rest as it was.",
        urlCleanerRulesAddButton: "Add",
        urlCleanerRulesRemoveButton: "Delete name",
        urlCleanerRulesRemoveSiteButton: "Turn off every rule for this site",
        urlCleanerRulesRestoreSiteButton: "Turn on every rule for this site",
        urlCleanerRemovedFormat: "Removed %@",
        switcherSearchPin: "Pin search with S",
        switcherSearchPinCaption: "S starts a search and pins the switcher open, so typing no longer produces special characters when your shortcut uses ⌥, and a search starting with Q or W no longer closes the window or quits the app by mistake.",
        invertVerticalScroll: "Invert vertical scrolling",
        invertHorizontalScroll: "Invert horizontal scrolling",
        scrollHorizontalName: "Scroll sideways while holding a key",
        scrollHorizontalModifierLabel: "Modifier key",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Hold only the selected modifier to scroll the vertical mouse wheel horizontally. Other key combinations are unchanged.",
        switcherShowShortcutHints: "Show shortcut hints",
        switcherShowShortcutHintsCaption: "Shows the app and window shortcuts below the icons.",
        uninstallerHomebrewPackageFormat: "%@ will also be removed from Homebrew.",
        shelfEdgeToggle: "Open near a screen edge",
        shelfEdgeCaption: "Drag a file toward the screen edge to peek the shelf in. Drop it there, or pull back and it retreats.",
        focusFollowsMouseName: "Focus follows mouse",
        focusFollowsMouseCaption: "Focuses the window under the pointer.",
        focusFollowsMouseDelay: "Hover delay",
        focusFollowsMouseRaise: "Bring the window to the front",
        focusFollowsMouseWaitForStop: "Wait for the pointer to stop",
        switcherMinimizedPlacementLabel: "Minimized windows",
        switcherTreatHiddenAppsLikeMinimized: "Treat hidden apps like minimized windows",
        switcherMinimizedPlacementNormal: "Normal ordering",
        switcherMinimizedPlacementEnd: "Place at end",
        switcherMinimizedPlacementHidden: "Hide",
        switcherShowFullscreenWindows: "Show fullscreen windows",
        switcherScreenPlacementLabel: "Show on",
        switcherScreenPlacementPointer: "Display with the pointer",
        switcherScreenPlacementMenuBar: "Display with the menu bar",
        switcherScreenPlacementActiveWindow: "Display with the active window",
        switcherScreenPlacementCaption: "Which display the switcher opens on when more than one is connected.",
        switcherCurrentDisplayOnly: "Show only the current display",
        switcherCurrentDisplayOnlyCaption: "Lists only windows on the display under the pointer. If that display has no windows, the switcher does not open.",
        smoothScrollResponseLabel: "Response",
        smoothScrollCoastLabel: "Coast",
        mouseAccelerationName: "Disable mouse acceleration",
        mouseAccelerationCaption: "Removes pointer acceleration for connected mice. Your previous setting returns when this is turned off or Vorssaint quits.",
        linearScrollName: "Linear scrolling",
        linearScrollCaption: "Every notch of the mouse wheel scrolls the same distance, no matter how fast it spins. The trackpad is not affected.",
        linearScrollLinesLabel: "Lines per step",
        shelfClearOnClose: "Clear when closed",
        shelfClearOnCloseCaption: "Empties the shelf only when you click its close button. Automatic hiding and collapsing keep the items.",
        shelfShortcutFinderSelection: "Add the Finder selection with the shortcut",
        shelfShortcutFinderSelectionCaption: "With Finder in front, the shortcut opens the shelf with the selected files already in it. With nothing selected, it opens as usual.",
        spacesOrderName: "Keep Spaces in a fixed order",
        spacesOrderCaption: "Stops macOS from rearranging Spaces by most recent use, so they stay in the order you set. Your previous setting returns when this is turned off. The Dock may restart once to apply the change."
    )
}
