import { defineLocale } from './define-locale'

// Swedish desktop translation. Missing new keys deliberately fall back to
// English while the catalogue catches up with the rapidly changing UI.
export const sv = defineLocale({
  common: {
    apply: 'Tillämpa',
    back: 'Tillbaka',
    save: 'Spara',
    saving: 'Sparar…',
    cancel: 'Avbryt',
    change: 'Ändra',
    choose: 'Välj',
    clear: 'Rensa',
    close: 'Stäng',
    collapse: 'Fäll ihop',
    confirm: 'Bekräfta',
    connect: 'Anslut',
    connecting: 'Ansluter',
    continue: 'Fortsätt',
    copied: 'Kopierat',
    copy: 'Kopiera',
    copyFailed: 'Det gick inte att kopiera',
    delete: 'Ta bort',
    docs: 'Dokumentation',
    done: 'Klar',
    error: 'Fel',
    expand: 'Fäll ut',
    failed: 'Misslyckades',
    formatJson: 'Formatera JSON',
    free: 'Ledigt',
    loading: 'Läser in…',
    notSet: 'Inte angivet',
    refresh: 'Uppdatera',
    remove: 'Ta bort',
    replace: 'Ersätt',
    retry: 'Försök igen',
    run: 'Kör',
    send: 'Skicka',
    set: 'Ange',
    skip: 'Hoppa över',
    update: 'Uppdatera',
    tryHint: term => `Prova ”${term}”`,
    on: 'På',
    off: 'Av'
  },
  fileMenu: {
    revealFinder: 'Visa i Finder',
    revealExplorer: 'Visa i Utforskaren',
    revealFileManager: 'Öppna innehållande mapp',
    revealInSidebar: 'Visa i filträdet',
    copyPath: 'Kopiera sökväg',
    copyRelativePath: 'Kopiera relativ sökväg',
    download: 'Hämta',
    downloadSaved: 'Sparad',
    downloadFailed: 'Hämtningen misslyckades',
    rename: 'Byt namn…',
    delete: 'Ta bort',
    renameTitle: 'Byt namn',
    renameLabel: 'Nytt namn',
    deleteTitle: name => `Ta bort ”${name}”?`,
    deleteBody: 'Detta kan inte ångras.',
    pathCopied: 'Sökvägen kopierades'
  },
  boot: {
    ready: 'Hermes Desktop är redo',
    desktopBootFailedWithMessage: message => `Starten av skrivbordsappen misslyckades: ${message}`,
    steps: { connectingGateway: 'Ansluter direkt till skrivbordsgateway', loadingSettings: 'Läser in Hermes-inställningar', loadingSessions: 'Läser in senaste sessionerna', retryingRemoteBackend: 'Återansluter till Hermes fjärrserverdel…', startingDesktopConnection: 'Startar skrivbordsanslutning', startingHermesDesktop: 'Startar Hermes Desktop…' },
    errors: { backgroundExited: 'Hermes bakgrundsprocess avslutades.', backgroundExitedDuringStartup: 'Hermes bakgrundsprocess avslutades under start.', backendStopped: 'Serverdelen stoppades', desktopBootFailed: 'Starten av skrivbordsappen misslyckades', gatewayConnectionLost: 'Anslutningen till gatewayen bröts', gatewayConnectionLostDetail: 'Försöker fortfarande igen i bakgrunden. Du kan fortsätta läsa och skriva utkast — öppna gateway-inställningarna om det kvarstår.', gatewaySignInRequired: 'Inloggning till gateway krävs', ipcBridgeUnavailable: 'Skrivbordsappens IPC-brygga är inte tillgänglig.' },
    failure: { title: 'Hermes kunde inte starta', description: 'Gatewayen i bakgrunden startade inte. Prova ett av återställningsstegen nedan. Inget här tar bort dina chattar eller inställningar.', remoteTitle: 'Inloggning till fjärrgateway krävs', remoteDescription: 'Din session för fjärrgatewayen har löpt ut. Logga in igen för att återansluta. Inget här tar bort dina chattar eller inställningar.', retry: 'Försök igen', repairInstall: 'Reparera installation', useLocalGateway: 'Använd lokal gateway', gatewaySettings: 'Gateway-inställningar', back: 'Tillbaka', openLogs: 'Öppna loggar', repairHint: 'Reparation kör installationsprogrammet på nytt och kan ta några minuter på en ny dator.', remoteSignInHint: signInLabel => `Loggar ut från den sparade fjärrsessionen i webbläsaren och öppnar sedan ${signInLabel}. Använd lokal gateway för att växla till den medföljande serverdelen i stället.`, signOutAndSignIn: 'Logga ut och logga in', remoteFailureHint: 'Kontrollera gatewayens URL och inloggning under Gateway-inställningar, eller växla till den lokala gatewayen.', cloudDownTitle: 'Nous Cloud-agenten är nere', cloudDownDescription: 'Den Nous-hanterade molnagent som gatewayen ansluter till returnerar ett serverfel. Den kan inte startas om härifrån — kontrollera dess status, växla till den lokala gatewayen eller be om support.', cloudDownHint: 'Knapparna nedan öppnar Nous Portal (instansstatus och kontroller) och vår Discord för support.', cloudDownCheckPortal: 'Kontrollera Portal-status', cloudDownDiscord: 'Få hjälp på Discord', hideRecentLogs: 'Dölj senaste loggar', showRecentLogs: 'Visa senaste loggar', signedInTitle: 'Inloggad', signedInMessage: 'Återansluter till fjärrgatewayen…', signInIncompleteTitle: 'Inloggningen slutfördes inte', signInIncompleteMessage: 'Inloggningsfönstret stängdes innan autentiseringen slutfördes.', signInFailed: 'Inloggningen misslyckades', signInToRemoteGateway: 'Logga in till fjärrgateway', signInWithProvider: provider => `Logga in med ${provider}`, identityProvider: 'din identitetsleverantör' }
  },
  notifications: {
    region: 'Aviseringar', hide: 'Dölj', show: 'Visa', more: count => `${count} ytterligare ${count === 1 ? 'avisering' : 'aviseringar'}`, clearAll: 'Rensa alla', dismiss: 'Avfärda avisering', details: 'Detaljer', copyDetail: 'Kopiera detalj', copyDetailFailed: 'Det gick inte att kopiera aviseringsdetalj', backendOutOfDateTitle: 'Serverdelen är inaktuell', backendOutOfDateMessage: 'Din Hermes-serverdel är äldre än denna skrivbordsversion och kanske inte fungerar korrekt. Uppdatera dem så att de matchar.', installMethodUnsupportedTitle: 'Installationsmetoden stöds inte', updateHermes: 'Uppdatera Hermes', updateReadyTitle: 'Uppdatering redo', updateReadyMessage: count => `${count} ny${count === 1 ? '' : 'a'} ändring${count === 1 ? '' : 'ar'} är tillgänglig${count === 1 ? '' : 'a'}.`, updateReadyMessageUnknown: 'En ny uppdatering är tillgänglig.', seeWhatsNew: 'Se vad som är nytt',
    mcp: { needsAuthTitle: 'MCP-server behöver autentiseras igen', needsAuthMessage: name => `${name} MCP behöver autentiseras igen.`, errorTitle: 'MCP-server kan inte nås', errorMessage: name => `${name} MCP klarade inte sin hälsokontroll.`, signIn: 'Logga in', view: 'Visa' },
    errors: { elevenLabsNeedsKey: 'ElevenLabs STT behöver ELEVENLABS_API_KEY.', elevenLabsRejectedKey: 'ElevenLabs avvisade API-nyckeln (401).', diskFull: 'Disken är full — frigör utrymme och försök igen.', gatewayAuthFailed: 'Gateway-autentisering misslyckades — kontrollera din API_SERVER_KEY.', methodNotAllowed: 'Skrivbordsserverdelen avvisade begäran (405 Method Not Allowed). Försök att starta om Hermes Desktop.', microphonePermission: 'Behörighet till mikrofonen nekades.', openaiRejectedApiKey: 'OpenAI avvisade API-nyckeln.', openaiRejectedApiKeyWithStatus: status => `OpenAI avvisade API-nyckeln (${status} invalid_api_key).`, openaiTtsNeedsKey: 'OpenAI TTS behöver VOICE_TOOLS_OPENAI_KEY eller OPENAI_API_KEY.', codeSkewRestartRequired: 'Den här serverdelen kör gammal kod efter en uppdatering. Starta om den för att läsa in den nya koden.' },
    voice: { configureSpeechToText: 'Konfigurera tal till text för att använda röstläge.', couldNotStartSession: 'Det gick inte att starta röstsession', microphoneAccessDenied: 'Åtkomst till mikrofonen nekades.', microphoneConstraintsUnsupported: 'Mikrofonbegränsningar stöds inte av denna enhet.', microphoneFailed: 'Mikrofonen misslyckades', microphoneInUse: 'Mikrofonen används redan av en annan app.', microphonePermissionDenied: 'Behörighet till mikrofonen nekades.', microphoneStartFailed: 'Det gick inte att starta mikrofoninspelning.', microphoneUnsupported: 'Den här körmiljön stöder inte mikrofoninspelning.', noMicrophone: 'Ingen mikrofon hittades.', noSpeechDetected: 'Inget tal upptäcktes', playbackFailed: 'Röstuppspelning misslyckades', recordingFailed: 'Röstinspelning misslyckades', sayStopToEnd: phrase => `Säg ”${phrase}” för att avsluta röstchatten.`, transcriptionFailed: 'Taligenkänning misslyckades', transcriptionUnavailable: 'Taligenkänning är inte tillgänglig ännu.', tryRecordingAgain: 'Försök spela in igen.', unavailable: 'Röst är inte tillgänglig' },
    native: { approvalTitle: 'Godkännande krävs', approveAction: 'Godkänn', rejectAction: 'Avvisa', inputTitle: 'Inmatning krävs', inputBody: 'Hermes väntar på ditt svar.', turnDoneTitle: 'Hermes är klar', turnDoneBody: '', turnErrorTitle: 'Körningen misslyckades', backgroundDoneTitle: 'Bakgrundsuppgiften är klar', backgroundFailedTitle: 'Bakgrundsuppgiften misslyckades', creditsTitle: 'Krediter' }
  },
  remoteDisplayBanner: { message: reason => `Programvarurendering är aktiv — fjärrskärm upptäcktes (${reason}). GPU-acceleration är inaktiverad för att förhindra flimmer.` },
  billingBlock: { titleNous: 'Slut på Nous-krediter', titleProvider: provider => `Slut på krediter — ${provider}`, fallbackMessage: 'Ditt konto har slut på krediter. Lägg till krediter för att fortsätta.', openBilling: 'Öppna fakturering', addCredits: 'Lägg till krediter', dismiss: 'Avfärda' },
  sendDiagnostics: {
    title: 'Skicka diagnostik till Nous',
    privacyNotice: 'Detta laddar upp ett felsökningspaket till Nous interna lagring (inte en offentlig inklistring). Det innehåller systeminformation (operativsystem, versioner, leverantör, vilka API-nycklar som är konfigurerade — aldrig själva nycklarna) och fullständiga agent-, gateway- och skrivbordsloggar (upp till 512 kB vardera), som sannolikt innehåller konversationsinnehåll, verktygsutdata och filsökvägar. Hemligheter maskeras före uppladdning. Paketet kan endast ses av Nous personal och tillåtna Discord-moderatorer och raderas automatiskt efter 14 dagar.',
    upload: 'Ladda upp', uploading: 'Laddar upp…', cancel: 'Avbryt', close: 'Stäng', copyLink: 'Kopiera länk',
    uploadIdFallback: id => `Ingen visningslänk returnerades — uppge uppladdnings-id ${id} till supporten`,
    doneTitle: 'Diagnostik skickad', doneDescription: 'Ditt paket laddades upp privat. Dela länken nedan i din supporttråd så att teamet kan se dina loggar.',
    failedTitle: 'Uppladdningen misslyckades', failedHint: 'Du kan också köra `hermes debug share --nous` i en terminal, eller `hermes debug share --local` för att skriva ut rapporten utan uppladdning.',
    handoffLead: 'Fortsätt diskussionen i:', links: { github: 'GitHub-ärenden', portal: 'Nous Portal-support', discord: 'Discord' }
  },
  titlebar: {
    hideSidebar: 'Dölj sidofält', showSidebar: 'Visa sidofält', search: 'Sök', searchTitle: 'Sök sessioner, vyer och åtgärder', swapSidebarSides: 'Byt sida för sidofält', hideRightSidebar: 'Dölj högra sidofältet', showRightSidebar: 'Visa högra sidofältet',
    unreadSessions: count => count === 1 ? '1 oläst session' : `${count} olästa sessioner`, muteHaptics: 'Stäng av haptik', unmuteHaptics: 'Slå på haptik', openSettings: 'Öppna inställningar', openStarmap: 'Öppna minnesgraf', enterHud: 'HUD-läge', exitHud: 'Avsluta HUD-läge', resetHudLayout: 'Återställ HUD-storlek och -position', layoutEditor: 'Layoutredigerare', layoutEditorTitle: mod => `Layoutredigerare — ${mod}-klick återställer layouten`
  },
  keybinds: {
    title: 'Tangentbordsgenvägar', subtitle: open => `Klicka på en genväg för att ändra den · ${open} öppnar panelen igen.`, search: 'Sök genvägar…', rebind: 'Ändra tangentbindning', reset: 'Återställ standard', resetAll: 'Återställ alla', pressKey: 'Tryck på en tangent…', set: 'ange', conflictWith: label => `Är också bunden till ”${label}”`,
    categories: { composer: 'Skrivfält', profiles: 'Profiler', session: 'Session', navigation: 'Navigering', view: 'Vy' },
    actions: {
      'keybinds.openPanel': 'Öppna tangentbordsgenvägar', 'nav.commandPalette': 'Öppna kommandopalett', 'nav.commandCenter': 'Öppna kommandocenter', 'nav.settings': 'Öppna inställningar', 'nav.profiles': 'Öppna profiler', 'nav.skills': 'Öppna färdigheter', 'nav.messaging': 'Öppna meddelanden', 'nav.artifacts': 'Öppna artefakter', 'nav.cron': 'Öppna schemalagda jobb', 'nav.agents': 'Öppna agenter',
      'session.new': 'Ny session', 'session.newTab': 'Ny sessionsflik', 'session.newWindow': 'Nytt fönster', 'session.next': 'Nästa session', 'session.prev': 'Föregående session',
      'session.slot.1': 'Växla till senaste session 1', 'session.slot.2': 'Växla till senaste session 2', 'session.slot.3': 'Växla till senaste session 3', 'session.slot.4': 'Växla till senaste session 4', 'session.slot.5': 'Växla till senaste session 5', 'session.slot.6': 'Växla till senaste session 6', 'session.slot.7': 'Växla till senaste session 7', 'session.slot.8': 'Växla till senaste session 8', 'session.slot.9': 'Växla till senaste session 9',
      'session.focusSearch': 'Sök sessioner', 'session.togglePin': 'Fäst/lossa aktuell session', 'session.archive': 'Arkivera aktuell session', 'workspace.newWorktree': 'Ny arbetskopia', 'workspace.openFolder': 'Öppna mapp som projekt',
      'composer.focus': 'Fokusera skrivfältet', 'composer.modelPicker': 'Öppna modellväljare', 'composer.voice': 'Starta/stoppa röstsamtal',
      'view.toggleSidebar': 'Växla sessionssidofält', 'view.toggleRightSidebar': 'Växla filbläddrare', 'view.toggleReview': 'Växla granskningspanel', 'view.toggleStatusbar': 'Växla statusrad', 'view.toggleTabStrip': 'Växla flikar', 'view.showFiles': 'Visa filbläddrare', 'view.showBrowser': 'Öppna webbläsare', 'view.toggleHud': 'Växla HUD-läge', 'hud.snapToPointer': 'Flytta HUD till pekaren (globalt när HUD är öppet)', 'view.showTerminal': 'Växla terminal', 'view.newTerminal': 'Ny terminal', 'view.nextTerminal': 'Nästa terminal', 'view.prevTerminal': 'Föregående terminal', 'view.closeTerminal': 'Stäng terminal', 'view.selectionToComposer': 'Skicka markering till skrivfältet', 'view.terminalCopy': 'Kopiera terminalmarkering', 'view.terminalPaste': 'Klistra in i terminal', 'view.closeTab': 'Stäng flik', 'view.reopenTab': 'Öppna stängd flik igen', 'view.flipPanes': 'Byt sida för sidofält', 'view.findInPage': 'Sök på sidan', 'view.findNext': 'Sök nästa träff', 'view.findPrevious': 'Sök föregående träff', 'appearance.toggleMode': 'Växla ljust/mörkt',
      'profile.default': 'Växla till standardprofil', 'profile.switch.1': 'Växla till profil 1', 'profile.switch.2': 'Växla till profil 2', 'profile.switch.3': 'Växla till profil 3', 'profile.switch.4': 'Växla till profil 4', 'profile.switch.5': 'Växla till profil 5', 'profile.switch.6': 'Växla till profil 6', 'profile.switch.7': 'Växla till profil 7', 'profile.switch.8': 'Växla till profil 8', 'profile.switch.9': 'Växla till profil 9', 'profile.switch.10': 'Växla till profil 10', 'profile.switch.11': 'Växla till profil 11', 'profile.switch.12': 'Växla till profil 12', 'profile.switch.13': 'Växla till profil 13', 'profile.switch.14': 'Växla till profil 14', 'profile.switch.15': 'Växla till profil 15', 'profile.switch.16': 'Växla till profil 16', 'profile.switch.17': 'Växla till profil 17', 'profile.switch.18': 'Växla till profil 18', 'profile.next': 'Nästa profil', 'profile.prev': 'Föregående profil', 'profile.toggleAll': 'Växla vy för alla profiler', 'profile.create': 'Skapa profil',
      'composer.send': 'Skicka meddelande', 'composer.newline': 'Infoga ny rad', 'composer.steer': 'Styr den pågående turen', 'composer.queue': 'Köa meddelande', 'composer.sendQueued': 'Skicka nästa köade tur', 'composer.mention': 'Referera till filer, mappar och URL:er', 'composer.slash': 'Palett för snedstreckskommandon', 'composer.help': 'Snabbhjälp', 'composer.history': 'Växla popup/historik', 'composer.cancel': 'Stäng popup · avbryt körning'
    }
  },
  settings: {
    closeSettings: 'Stäng inställningar', exportConfig: 'Exportera konfiguration', importConfig: 'Importera konfiguration', resetToDefaults: 'Återställ standardinställningar', resetConfirm: 'Återställ alla inställningar till Hermes standardvärden?', exportFailed: 'Exporten misslyckades', resetFailed: 'Återställningen misslyckades',
    nav: { providers: 'Leverantörer', providerAccounts: 'Konton', providerApiKeys: 'API-nycklar', providerCustomEndpoints: 'Anpassade ändpunkter', providerLocalModels: 'Lokala modeller', gateway: 'Gatewayer', apiKeys: 'Verktyg och nycklar', keybinds: 'Tangentbordsgenvägar', keysTools: 'Verktyg', keysSettings: 'Inställningar', mcp: 'MCP', archivedChats: 'Arkiverade chattar', about: 'Om', billing: 'Fakturering', notifications: 'Aviseringar', plugins: 'Insticksprogram' },
    plugins: {
      title: 'Insticksprogram för skrivbordet', blurb: 'Medföljer eller läggs i mappen desktop-plugins. Inaktivera för att avlasta dem direkt.', count: n => `${n} installerade`, openFolder: 'Öppna mapp för insticksprogram', rescan: 'Sök igen', reveal: 'Visa i filhanteraren', enable: 'Aktivera', disable: 'Inaktivera', failed: 'misslyckades', empty: 'Inga skrivbordsinsticksprogram är installerade ännu.', kinds: { bundled: 'medföljande', disk: 'på disk', runtime: 'körtid' },
      agent: { title: 'Agentinsticksprogram', blurb: 'Insticksprogram som du har installerat i Hermes-serverdelen – verktyg, färdigheter, MCP-servrar, krokar och snedstreckskommandon. Portabla program är Agent Plugins-paket (färdigheter och MCP-paket som även fungerar i andra agenter). Växlar tillämpas på nya sessioner.', appliesTo: 'Gäller för:', empty: 'Inga agentinsticksprogram är installerade ännu.', loadFailed: 'Kunde inte läsa in agentinsticksprogram', portable: 'portabelt', search: 'Sök insticksprogram…', noMatches: 'Inga insticksprogram matchar din sökning.', toggleFailed: name => `Kunde inte växla ${name}`, updateBackendToManage: 'Uppdatera Hermes-serverdelen för att hantera detta insticksprogram från skrivbordsappen.', sources: { bundled: 'medföljande', user: 'användare', git: 'git', project: 'projekt', entrypoint: 'pip' } },
      installModal: { title: 'Installera insticksprogram', description: 'Granska vad förvaret innehåller innan du installerar något.', repoLabel: 'Förvar', includesHeading: 'Detta paket innehåller', agentLabel: 'Agentinsticksprogram', desktopLabel: 'Skrivbordsgränssnitt', agentTargetLocal: profile => `Installeras i serverdelen för ${profile} (~/.hermes/plugins/)`, agentTargetRemote: profile => `Installeras i den anslutna serverdelen för ${profile}`, desktopTarget: 'Installeras i denna apps lokala mapp desktop-plugins', desktopOnlyNote: 'Paket enbart för skrivbordet installerar inget agentinsticksprogram i serverdelen.', insecureWarning: 'Denna URL använder ett osäkert eller lokalt schema. Föredra https:// eller git@ för produktionsinstallationer.', securityHeading: 'Innan du installerar', securityIntro: 'Installera bara från källor du litar på – granska förvaret nedan om du vill se vad som läggs till.', sourceHeading: 'Källkod', viewRepository: 'Visa förvar', viewPluginFiles: 'Visa insticksprogramfiler', gitCloneLabel: 'Git-klonings-URL', enableAgent: 'Aktivera agentinsticksprogram efter installation', forceReinstall: 'Tvinga ominstallation (ersätt om redan installerat)', install: 'Installera', installing: 'Installerar…', probing: 'Granskar förvar…', probeUnavailable: 'Granskning av insticksprogram är inte tillgänglig i denna miljö.', desktopUnavailable: 'Installation av skrivbordsinsticksprogram är inte tillgänglig i denna miljö.', selectComponent: 'Välj minst en komponent att installera.', agentSuccess: name => `Agentinsticksprogrammet ${name} installerades`, desktopSuccess: name => `Skrivbordsinsticksprogrammet ${name} installerades`, agentFailed: 'Installationen av agentinsticksprogrammet misslyckades', desktopFailed: 'Installationen av skrivbordsinsticksprogrammet misslyckades', missingEnv: vars => `Saknade miljövariabler: ${vars}. Lägg till dem under Inställningar → Nycklar.` }
    },
    notifications: {
      title: 'Aviseringar', intro: 'Operativsystemets aviseringar (inte meddelanden i appen). Per enhet.', enableAll: 'Aktivera aviseringar', enableAllDesc: 'Av stänger av alla aviseringar nedan.', focusedHint: 'Slutförandeaviseringar utlöses endast medan Hermes är i bakgrunden.',
      kinds: { approval: { label: 'Godkännande krävs', description: 'Ett kommando väntar på att du ska godkänna eller avvisa det.' }, input: { label: 'Indata krävs', description: 'Hermes ställde en fråga eller behöver ett lösenord eller en hemlighet.' }, turnDone: { label: 'Svar klart', description: 'En tur blev klar medan Hermes var i bakgrunden.' }, turnError: { label: 'Turen misslyckades', description: 'Fel i bakgrundsturer.' }, backgroundDone: { label: 'Bakgrundsaktivitet klar', description: 'Ett terminalkommando i bakgrunden slutfördes.' }, credits: { label: 'Kreditaviseringar', description: 'Kreditåtkomst har pausats eller återställts.' }, plugin: { label: 'Aviseringar från insticksprogram', description: 'Ett skrivbordsinsticksprogram skickade en avisering medan Hermes var i bakgrunden.' } },
      test: 'Skicka testavisering', testTitle: 'Hermes', testBody: 'Aviseringarna fungerar.', testSent: 'Testet skickades. Om inget visas, kontrollera operativsystemets aviseringsbehörigheter och Fokus/Stör ej.', testUnsupported: 'Detta system stöder inte inbyggda aviseringar.', completionSoundTitle: 'Slutförandeljud', completionSoundDesc: 'Spelas upp när en agenttur avslutas. Välj en förinställning och förhandsgranska den här.', completionSoundPreview: 'Förhandsgranska'
    },
    sections: { model: 'Modell', chat: 'Chatt', appearance: 'Utseende', workspace: 'Arbetsyta', safety: 'Säkerhet', memory: 'Minne och kontext', voice: 'Röst', advanced: 'Avancerat' },
    searchPlaceholder: { about: 'Om Hermes Desktop', config: 'Sök inställningar…', gateway: 'Gatewayanslutning…', keys: 'Sök API-nycklar…', mcp: 'Sök MCP-servrar…', sessions: 'Sök arkiverade sessioner…' },
    modeOptions: { light: { label: 'Ljust', description: 'Ljusa skrivbordsytor' }, dark: { label: 'Mörkt', description: 'Arbetsyta med låg bländning' }, system: { label: 'System', description: 'Följ operativsystemets utseende' } },
    mcp: {
      loading: 'Läser in MCP-servrar…', failedLoad: 'MCP-konfigurationen kunde inte läsas in', nameRequiredTitle: 'Namn krävs', nameRequiredMessage: 'Ge MCP-servern en konfigurationsnyckel.', objectRequired: 'Serverkonfigurationen måste vara ett JSON-objekt', invalidJson: 'Ogiltig MCP-JSON', saveFailed: 'Kunde inte spara', removeFailed: 'Kunde inte ta bort', gatewayUnavailableTitle: 'Gatewayen är inte tillgänglig', gatewayUnavailableMessage: 'Återanslut gatewayen innan MCP laddas om.', reloadedTitle: 'MCP-verktyg laddades om', reloadedMessage: 'Nya verktygsscheman gäller för nya turer.', reloadFailed: 'Kunde inte läsa om MCP', savedTitle: 'MCP-servern sparades', savedMessage: name => `${name} används efter omladdning av MCP.`, newServer: 'Ny server', reload: 'Läs om MCP', reloading: 'Läser om…', emptyTitle: 'Inga MCP-servrar', emptyDesc: 'Lägg till en stdio- eller HTTP-server för att exponera MCP-verktyg.', disabled: 'inaktiverad', editServer: 'Redigera server', name: 'Namn', serverJson: 'Server-JSON', remove: 'Ta bort', saveServer: 'Spara server', test: 'Testa anslutning', testing: 'Testar…', testOk: count => `Ansluten – ${count} ${count === 1 ? 'verktyg' : 'verktyg'} tillgängliga`, testFailed: 'Anslutningen misslyckades', enableServer: name => `Aktivera ${name}`, disableServer: name => `Inaktivera ${name}`, serverEnabled: name => `${name} är aktiverad – gäller för nya sessioner.`, serverDisabled: name => `${name} är inaktiverad – gäller för nya sessioner.`, toggleFailed: (name, enabled) => `Kunde inte ${enabled ? 'aktivera' : 'inaktivera'} ${name}`,
      tabServers: 'Servrar', tabCatalog: 'Katalog', catalogLoading: 'Läser in MCP-katalog…', catalogLoadFailed: 'Kunde inte läsa in MCP-katalogen', catalogEmpty: 'Inga katalogposter är tillgängliga.', catalogInstalled: 'Installerad', catalogEnabled: 'Aktiverad', catalogNeedsInstall: 'Behöver byggas', catalogInstall: 'Installera', catalogInstalling: 'Installerar…', catalogInstallStarted: name => `Installerar ${name}… gäller för nya sessioner när det är klart.`, catalogInstallFailed: name => `Kunde inte installera ${name}`, catalogEnvPrompt: name => `${name} kräver inloggningsuppgifter`, catalogEnvRequired: 'Fyll i de obligatoriska värdena före installationen.', capabilitySummary: (tools, prompts, resources) => `${[`${tools} verktyg`, ...(prompts ? [`${prompts} promptar`] : []), ...(resources ? [`${resources} resurser`] : [])].join(', ')} aktiverade`, costTokens: tokens => `~${tokens} tok/anrop`, usage30d: uses => `${uses} användningar/30 d`, unusedPill: 'oanvänd', statusConnecting: 'Ansluter…', statusNeedsAuth: 'Autentisering krävs', statusError: 'Fel', statusOff: 'Av', allServers: 'Alla servrar', authenticatedTitle: 'Autentiserad', authenticatedMessage: (server, count) => `${server}: ${count} verktyg`, waitingForBrowser: 'Väntar på webbläsaren…', authenticate: 'Autentisera', unsavedConnect: 'Inte sparad – spara mcp.json för att ansluta.', enableTool: tool => `Aktivera ${tool}`, disableTool: tool => `Inaktivera ${tool}`, noOutput: 'Ingen utdata ännu.',
      deepLinkTitle: 'Lägg till MCP-server?', deepLinkDescription: 'En länk begärde att denna MCP-server skulle läggas till i Hermes. Granska den exakta konfigurationen nedan – den kommer från länken, inte från Hermes.', deepLinkStdioWarning: 'Denna server kör en lokal process på datorn med kommandot nedan. Fortsätt bara om du litar på källan.', deepLinkConfirm: 'Lägg till server', deepLinkNameInvalid: 'Namn får innehålla 1–64 bokstäver, siffror, punkter, bindestreck eller understreck.', deepLinkNameConflict: name => `En server med namnet ${name} finns redan – välj ett annat namn eller avbryt.`, deepLinkErrorTitle: 'MCP-installationslänken avvisades', deepLinkErrorName: 'Länkens servernamn saknas eller är ogiltigt.', deepLinkErrorConfig: 'Länkens konfiguration är inte giltig base64-kodad JSON.', deepLinkErrorShape: 'Konfigurationen måste vara ett JSON-objekt med strängfältet `url` eller `command`.', deepLinkErrorUrl: 'Endast server-URL:er med http:// och https:// tillåts.', deepLinkErrorTooLarge: 'Konfigurationens nyttolast överskrider gränsen på 32 KB.', importButton: 'Importera', importPlaceholder: 'Klistra in ett mcp.json-utdrag, npx-/docker-kommando, en rad från claude mcp add, URL eller Cursor-länk…', importNoMatch: 'Ingen serverkonfiguration kunde identifieras i den inklistrade texten.', importConfirm: 'Lägg till i mcp.json', importConfirmMany: count => `Lägg till ${count} servrar i mcp.json`
    },
    model: {
      loading: 'Läser in modellkonfiguration…', appliesDesc: 'Gäller för nya sessioner. Använd modellväljaren i skrivfältet för att byta modell i den aktiva chatten.', provider: 'Leverantör', model: 'Modell', applying: 'Tillämpar…', defaultsLabel: 'Standardvärden', reasoning: 'Resonemang', reasoningOff: 'Av', defaultsFailed: 'Kunde inte spara modellens standardvärden', loadFailed: 'Kunde inte läsa in modeller', restartRequired: 'Den här serverdelen kör gammal kod efter en uppdatering. Starta om den för att läsa in den nya koden.', restartBackend: 'Starta om serverdelen', restartingBackend: 'Startar om serverdelen…', restartFailed: 'Kunde inte starta om serverdelen', auxiliaryTitle: 'Hjälpmodeller', resetAllToMain: 'Återställ alla till huvudmodellen', auxiliaryDesc: 'Hjälpuppgifter körs som standard med huvudmodellen. Tilldela en särskild modell till en uppgift för att åsidosätta det.', setToMain: 'Använd huvudmodellen', change: 'Ändra', autoUseMain: 'automatiskt · använd huvudmodellen', providerDefault: '(leverantörens standard)', fallbackAdd: 'Lägg till reservmodell', fallbackEmpty: 'Inga reservmodeller – standardmodellen används om den inte misslyckas.', notInCatalog: 'finns inte i leverantörens modellista – anrop kan falla tillbaka till en reserv.',
      tasks: {
        vision: { label: 'Syn', hint: 'Bildanalys' }, compression: { label: 'Komprimering', hint: 'Komprimering av kontext' }, skills_hub: { label: 'Färdighetshubb', hint: 'Sökning efter färdigheter' }, approval: { label: 'Godkännande', hint: 'Smart automatiskt godkännande' }, mcp: { label: 'MCP', hint: 'Routning av MCP-verktyg' }, title_generation: { label: 'Rubrikgenerering', hint: 'Sessionsrubriker' }, review: { label: 'Granskning', hint: 'Underagent för /review' }, curator: { label: 'Kurator', hint: 'Granskning av färdighetsanvändning' }
      }
    },
    sessions: {
      loading: 'Läser in arkiverade sessioner…', archivedTitle: 'Arkiverade sessioner', archivedIntro: 'Arkiverade chattar döljs från sidofältet men behåller alla sina meddelanden. Ctrl/⌘-klicka på en chatt i sidofältet för att arkivera den.', emptyArchivedTitle: 'Inget arkiverat', emptyArchivedDesc: 'Arkivera en chatt för att dölja den här.', unarchive: 'Ta bort från arkiv', deletePermanently: 'Ta bort permanent', messages: count => `${count} ${count === 1 ? 'meddelande' : 'meddelanden'}`, restored: 'Återställd', deleteConfirm: title => `Ta bort ”${title}” permanent? Detta kan inte ångras.`, autoArchiveTitle: 'Arkivera inaktiva chattar automatiskt', autoArchiveDesc: 'Arkivera automatiskt chattar du inte har använt på ett tag. Fästa chattar arkiveras aldrig och inget tas bort – arkiverade chattar flyttas bara hit.', autoArchiveDaysLabel: 'Arkivera efter', autoArchiveDaysUnit: 'dagars inaktivitet', autoArchiveFailed: 'Kunde inte uppdatera automatisk arkivering', defaultDirTitle: 'Standardmapp för projekt', defaultDirDesc: 'Nya sessioner startar i denna mapp om du inte väljer en annan. Lämna den tom för att använda din hemmapp.', defaultDirUpdated: 'Standardmappen för projekt uppdaterades – starta en ny chatt (Ctrl/⌘+N) för att ändringen ska gälla', defaultsTo: label => `Standard: ${label}.`, change: 'Ändra', choose: 'Välj', clear: 'Rensa', notSet: 'Inte angiven', failedLoad: 'Kunde inte läsa in arkiverade sessioner', unarchiveFailed: 'Kunde inte ta bort från arkiv', deleteFailed: 'Kunde inte ta bort', updateDirFailed: 'Kunde inte uppdatera standardmappen', clearDirFailed: 'Kunde inte rensa standardmappen'
    }
  },
  findInPage: { next: 'Nästa träff', previous: 'Föregående träff' },
  artifactCard: { kind: { code: 'Kod', html: 'Interaktiv sida', svg: 'Grafik' }, generating: lines => `Skapar… ${lines} rader`, versionBadge: count => `${count} versioner`, open: 'Öppna' },
  artifactPreview: { versionOf: (current, total) => `v${current} av ${total}`, olderVersion: 'Äldre version', newerVersion: 'Nyare version', latest: 'Senaste', copyContent: 'Kopiera innehåll', download: 'Hämta', openInBrowser: 'Öppna i webbläsaren', openInBrowserFailed: 'Det gick inte att öppna i webbläsaren', missingTitle: 'Artefakten är inte tillgänglig', missingBody: 'Denna artefakt finns inte längre i det lokala registret.' },
  modelVisibility: { title: 'Modeller', search: 'Sök modeller', noAuthenticatedProviders: 'Inga autentiserade leverantörer.', addProvider: 'Lägg till leverantör…' },
  contextMenu: {
    link: { openInApp: 'Öppna i appens webbläsare', openExternal: 'Öppna i extern webbläsare', copyUrl: 'Kopiera URL', copyResolvedUrl: 'Kopiera löst URL' },
    image: { copyImage: 'Kopiera bild', copyImageAddress: 'Kopiera bildadress', saveImageAs: 'Spara bild som…' },
    edit: { cut: 'Klipp ut', paste: 'Klistra in', selectAll: 'Markera allt', addToDictionary: 'Lägg till i ordlistan' },
    page: { copyPageUrl: 'Kopiera sidans URL', inspectElement: 'Inspektera element' }
  },
  prompts: { gatewayDisconnected: 'Hermes gateway är inte ansluten', sudoSendFailed: 'Det gick inte att skicka sudo-lösenordet', secretSendFailed: 'Det gick inte att skicka hemligheten', sudoTitle: 'Administratörslösenord', sudoDesc: 'Hermes behöver ditt sudo-lösenord för att köra ett privilegierat kommando. Det skickas bara till din lokala agent.', sudoPlaceholder: 'sudo-lösenord', secretTitle: 'Hemlighet krävs', secretDesc: 'Hermes behöver en inloggningsuppgift för att fortsätta.', secretPlaceholder: 'hemligt värde' },
  errors: { genericFailure: 'Något gick fel', boundaryTitle: 'Något gick sönder i gränssnittet', boundaryDesc: 'Vyn stötte på ett oväntat fel. Dina chattar och inställningar är säkra.', reloadWindow: 'Läs om fönster', openLogs: 'Öppna loggar' },
  ui: { search: { clear: 'Rensa sökning' }, pagination: { label: 'sidindelning', previous: 'Föregående', previousAria: 'Gå till föregående sida', next: 'Nästa', nextAria: 'Gå till nästa sida' }, sidebar: { title: 'Sidofält', description: 'Visar sidofältet på mobilen.', toggle: open => `${open ? 'Visa' : 'Dölj'} sidofält` } },
  starmap: { title: 'Minnesgraf', subtitle: (nodes, clusters) => `${nodes} färdigheter i ${clusters} kategorier`, close: 'Stäng minnesgraf', refresh: 'Uppdatera', memory: 'Minne', filterAll: 'Alla', filterUsed: 'Använda', filterLearned: 'Inlärda', viewGraph: 'Graf', loadFailed: 'Kunde inte läsa in minnesgrafen', loading: 'Läser in…', emptyTitle: 'Inget inlärt ännu', emptyDesc: 'När Hermes bygger färdigheter och minnen för ditt arbete visas de här.', share: 'Dela karta', shareHint: 'Kopiera koden för att dela den här kartan eller klistra in en för att läsa in den. Den innehåller bara layouten, inte dina minnes- eller färdighetstexter.', shareTitle: 'Importera/exportera karta', sharePlaceholder: 'Klistra in en kartkod…', copy: 'Kopiera kartkod', copied: 'Kopierat!', importMap: 'Importera en karta', importBtn: 'Läs in', importEmpty: 'Klistra in en kartkod för att läsa in den.', importSuccess: nodes => `Läste in en karta med ${nodes} ${nodes === 1 ? 'nod' : 'noder'}.`, importedBadge: 'importerad karta', resetToMine: 'Tillbaka till min karta' },
  agents: { close: 'Stäng agenter', title: 'Startträd', subtitle: 'Direkt aktivitet för underagenter i den aktuella turen.', emptyTitle: 'Inga aktiva underagenter', emptyDesc: 'När en tur delegerar arbete strömmas underagenternas förlopp hit.', running: 'Körs', failed: 'Misslyckades', done: 'Klar', streaming: 'Strömmar', files: 'Filer', moreFiles: count => `+${count} fler filer`, delegation: index => `Delegering ${index}`, workers: count => `${count} arbetare`, workersActive: count => `${count} aktiva`, agentsCount: count => `${count} ${count === 1 ? 'agent' : 'agenter'}`, activeCount: count => `${count} aktiva`, failedCount: count => `${count} misslyckades`, toolsCount: count => `${count} verktyg`, filesCount: count => `${count} filer`, updatedAgo: age => `uppdaterad ${age}`, ageNow: 'nu', ageSeconds: seconds => `${seconds} s sedan`, ageMinutes: minutes => `${minutes} min sedan`, ageHours: hours => `${hours} h sedan`, ageDays: days => `${days} d sedan`, durationSeconds: seconds => `${seconds} s`, durationMinutes: (minutes, seconds) => `${minutes} min ${seconds} s`, tokens: value => `${value} tok` },
  artifacts: { search: 'Sök artefakter…', refresh: 'Uppdatera artefakter', refreshing: 'Uppdaterar artefakter', indexing: 'Indexerar artefakter från senaste sessioner', tabAll: 'Alla', tabImages: 'Bilder', tabFiles: 'Filer', tabLinks: 'Länkar', noArtifactsTitle: 'Inga artefakter hittades', noArtifactsDesc: 'Genererade bilder och filutdata visas här när sessioner skapar dem.', failedLoad: 'Det gick inte att läsa in artefakter', openFailed: 'Det gick inte att öppna', itemsImage: 'bilder', itemsLink: 'länkar', itemsFile: 'filer', itemsGeneric: 'objekt', zero: '0', rangeOf: (start, end, total) => `${start}–${end} av ${total}`, goToPage: (itemLabel, page) => `Gå till ${itemLabel}-sida ${page}`, colTitleLink: 'Länktitel', colTitleFile: 'Namn', colTitleDefault: 'Titel/namn', colLocationLink: 'URL', colLocationFile: 'Sökväg', colLocationDefault: 'Plats', colSession: 'Session', kindImage: 'bild', kindFile: 'fil', kindLink: 'länk', chat: 'Chatt', copyUrl: 'Kopiera URL', copyPath: 'Kopiera sökväg' },
  modelPicker: { title: 'Byt modell', current: 'aktuell:', unknown: '(okänd)', search: 'Filtrera leverantörer och modeller…', noModels: 'Inga modeller hittades.', addProvider: 'Lägg till leverantör', loadFailed: 'Kunde inte läsa in modeller', loadingIntoMemory: 'Läser in i minnet', downloading: 'Hämtar', localDownloadsHeading: 'Lokalt', noAuthenticatedProviders: 'Inga autentiserade leverantörer.', pro: 'Pro', proNeedsSubscription: 'Pro-modeller kräver en betald Nous-prenumeration.', free: 'Gratis', freeTier: 'Gratisnivå', priceTitle: 'In-/utpris per miljon token', wasPrice: 'tidigare' },
  rightSidebar: { aria: 'Högra sidofältet', panelsAria: 'Paneler i högra sidofältet', files: 'Filsystem', terminal: 'Terminal', noFolderSelected: 'Ingen mapp vald', changeCwdTitle: 'Byt arbetskatalog', remotePickerTitle: 'Välj fjärrmapp', remotePickerDescription: 'Bläddra bland mappar på den anslutna serverdelen.', remotePickerSelect: 'Välj mapp', folderTip: cwd => cwd, openFolder: 'Öppna mapp', refreshTree: 'Uppdatera träd', collapseAll: 'Fäll ihop alla mappar', previewUnavailable: 'Förhandsvisning saknas', couldNotPreview: path => `Kunde inte förhandsvisa ${path}`, noProjectTitle: 'Inget projekt', noProjectBody: 'Öppna ett projekt för att bläddra bland dess filer och granska ändringar.', noProjectOpen: 'Inget projekt är öppet', noDiffs: 'Inga skillnader', unreadableTitle: 'Oläsbar', unreadableBody: error => `Kunde inte läsa denna mapp (${error}).`, emptyTitle: 'Tom', emptyBody: 'Den här mappen är tom.', treeErrorTitle: 'Trädfel', treeErrorBody: 'Filträdet stötte på ett fel när mappen skulle visas.', tryAgain: 'Försök igen', loadingTree: 'Läser in filträd', loadingFiles: 'Läser in filer', terminalHide: 'Dölj terminal', terminalsAria: 'Terminaler', terminalNew: 'Ny terminal', terminalCloseOthers: 'Stäng övriga', terminalCloseAll: 'Stäng alla', addToChat: 'Lägg till i chatten' },
  zones: { showTabStrip: 'Visa flikar', hideTabStrip: 'Dölj flikar', showStripTab: title => `Visa ${title}`, hideStripTab: title => `Dölj ${title}`, lastTabKeptTitle: 'Sista fliken behålls', lastTabKeptBody: 'Den här zonen behöver minst en synlig flik. Visa en annan flik först eller fäll ihop hela sidofältet.', toggleStripTab: title => `Växla fliken ${title}`, minimize: 'Minimera', restore: 'Återställ', closeRunningTitle: 'Stäng pågående flik?', closeRunningBody: 'Den här chatten arbetar fortfarande (eller väntar på din inmatning). Att stänga fliken döljer den — sessionen behåller sitt förlopp och kan öppnas igen från sidofältet.', closeRunningConfirm: 'Stäng flik', reload: 'Läs om', closeOthers: 'Stäng övriga', closeToRight: 'Stäng åt höger', closeAll: 'Stäng alla', newSessionTab: 'Ny sessionsflik', newTab: 'Ny flik', pluginDisabled: pluginId => `Insticksprogrammet ”${pluginId}” är inaktiverat`, pluginDisabledBody: 'Aktivera det igen under Inställningar → Insticksprogram för att få tillbaka panelen.', missingPane: paneId => `panel saknas: ${paneId}`, editTitle: 'Layouter', editHint: 'Välj en layout eller dra paneler mellan zoner.', reset: 'Återställ', templates: 'Mallar', custom: 'Anpassad', newGridLayout: 'Ny rutnätslayout', saveCurrentAs: 'Spara aktuell ordning som mall', nameLayoutPlaceholder: 'Namnge denna layout…', deletePreset: name => `Ta bort ${name}`, zoneEditorTitle: 'Zonredigerare', editorHintPre: 'klicka för att dela · ', editorHintPost: ' vänder linjen · dra över zoner för att slå ihop · dra delade kanter för att ändra storlek', templateColumns: 'Kolumner', templateRows: 'Rader', templateGrid: 'Rutnät', templatePriority: 'Prioritet', zoneTag: index => `zon ${index}`, mergeZones: count => `Slå ihop ${count} zoner`, customZoneName: count => `Anpassad zon med ${count}`, layoutNamePlaceholder: fallback => `Layoutnamn (${fallback})`, saveApply: 'Spara och tillämpa', notExpressible: 'den här ordningen är sammankopplad (vindkvarn) — kan ännu inte uttryckas som nästlade delningar', zoneCount: count => `${count} zoner`, tabCount: count => `${count} flikar` },
  tips: { close: 'Visa inte detta tips igen', items: { 'new-session': { title: 'Börja från början', text: 'En ny chatt får eget sammanhang, terminal och arbetskatalog.' }, skills: { title: 'Lär den en gång', text: 'Färdigheter är mappar med instruktioner som Hermes läser in när arbetet kräver dem.' }, messaging: { title: 'Hermes borta från skrivbordet', text: 'Anslut Telegram, Discord, Slack med flera — samma agent, samma minne.' }, artifacts: { title: 'Allt Hermes skapade', text: 'Bilder, filer och länkar från varje session, indexerade på ett ställe.' }, cron: { title: 'Arbete som kör sig självt', text: 'Schemalägg en prompt varje timme, natt eller enligt ett cron-uttryck.' }, 'command-palette': { title: 'En ruta för allt', text: 'Sessioner, inställningar, färdigheter och kommandon nås alla via paletten.' }, profiles: { title: 'Profiler är separata', text: 'Var och en är sin egen Hermes — egna nycklar, eget minne, egna sessioner.' }, 'composer-mentions': { title: 'Bifoga och kommendera', text: 'Skriv @ för att ta med en fil i konversationen, / för att köra ett kommando.' }, 'local-setup': { title: 'Datorn kan köra modeller lokalt', text: 'Din maskin kan köra en lokal modell. Chattar stannar på datorn och kostar inget.', action: 'Konfigurera' }, 'right-pane': { title: 'Arbetspanelen', text: 'Filer, terminal, granskning och appens webbläsare delar höger sida.' } } },
  language: { label: 'Språk', description: 'Välj språk för skrivbordsgränssnittet.', saving: 'Sparar språk…', saveError: 'Det gick inte att uppdatera språk', switchTo: 'Byt språk', searchPlaceholder: 'Sök språk…', noResults: 'Inga språk hittades' }
})
