import { defineLocale } from "./define-locale";

// Complete Swedish UI translation. `defineLocale` keeps future keys type-checked
// and supplies a safe fallback until they are translated in a follow-up.
export const sv = defineLocale({
  common: {
    save: "Spara",
    saving: "Sparar…",
    cancel: "Avbryt",
    close: "Stäng",
    confirm: "Bekräfta",
    delete: "Ta bort",
    refresh: "Uppdatera",
    retry: "Försök igen",
    search: "Sök…",
    loading: "Läser in…",
    create: "Skapa",
    creating: "Skapar…",
    set: "Ange",
    replace: "Ersätt",
    clear: "Rensa",
    live: "Direkt",
    off: "Av",
    enabled: "aktiverad",
    disabled: "inaktiverad",
    active: "aktiv",
    inactive: "inaktiv",
    unknown: "okänd",
    untitled: "Namnlös",
    none: "Ingen",
    form: "Formulär",
    noResults: "Inga resultat",
    of: "av",
    page: "Sida",
    msgs: "medd.",
    tools: "verktyg",
    match: "träff",
    other: "Övrigt",
    configured: "konfigurerad",
    removed: "borttagen",
    failedToToggle: "Det gick inte att växla",
    failedToRemove: "Det gick inte att ta bort",
    failedToReveal: "Det gick inte att visa",
    collapse: "Fäll ihop",
    expand: "Fäll ut",
    general: "Allmänt",
    messaging: "Meddelanden",
    gateway: "Gateway",
    gatewayHint:
      "Meddelandeplattformar, API-servern och webhooks konfigureras på sidan Kanaler. Dessa inställningar gäller för hela gatewayen (proxy-/vidarebefordringsläge och global tillåtelselista).",
    pluginLoadFailed:
      "Det gick inte att läsa in pluginets skript. Kontrollera fliken Nätverk (dashboard-plugins/…) och serverns pluginsökväg.",
    pluginNotRegistered:
      "Pluginets skript anropade inte register(), eller så uppstod ett fel i skriptet. Öppna webbläsarkonsolen för detaljer.",
  },
  app: {
    closeNavigation: "Stäng navigering",
    closeModelTools: "Stäng modell och verktyg",
    activeSessionsLabel: "Aktiva sessioner:",
    gatewayStatusLabel: "Gateway-status:",
    gatewayStrip: {
      failed: "Starten misslyckades",
      off: "Av",
      running: "Körs",
      starting: "Startar",
      stopped: "Stoppad",
    },
    nav: {
      analytics: "Analys",
      chat: "Chatt",
      config: "Konfiguration",
      cron: "Schemaläggning",
      documentation: "Dokumentation",
      keys: "Nycklar",
      logs: "Loggar",
      models: "Modeller",
      profiles: "Profiler",
      sessions: "Sessioner",
      skills: "Färdigheter",
    },
    modelToolsSheetSubtitle: "och verktyg",
    modelToolsSheetTitle: "Modell",
    navigation: "Navigering",
    openDocumentation: "Öppna dokumentation på en ny flik",
    openNavigation: "Öppna navigering",
    sessionsActiveCount: "{count} aktiva",
    statusOverview: "Statusöversikt",
    system: "System",
    webUi: "Webbgränssnitt",
    managingProfile: "Hanterar profil",
    currentProfileOption: "den här instrumentpanelen ({name})",
    managingProfileBanner:
      "Hanterar profilen ”{name}” — konfiguration, nycklar, färdigheter, MCP:er, modell och nya chattar tillhör den här profilen.",
    memoryOomRestartBanner:
      "Din agent startades om oväntat, troligen för att minnet tog slut. Långa sessioner och många samtidiga uppgifter ökar minnesanvändningen.",
    memoryCriticalBanner:
      "Din agent har nästan slut på minne och kan startas om. Överväg att stänga inaktiva sessioner eller utöka minnet.",
    memoryElevatedBanner: "Din agent har ont om minne.",
    diskCriticalBanner:
      "Agentens disk är nästan full. Nya meddelanden, minnen och inställningar kanske inte kan sparas.",
    diskElevatedBanner:
      "Agentens disk fylls. Överväg att rensa gamla sessioner eller utöka lagringsutrymmet.",
    dismiss: "Avfärda",
  },
  status: {
    actionFailed: "Åtgärden misslyckades",
    actionFinished: "Slutförd",
    actions: "Åtgärder",
    agent: "Agent",
    activeSessions: "Aktiva sessioner",
    connected: "Ansluten",
    connectedPlatforms: "Anslutna plattformar",
    disabled: "Inaktiverad",
    disconnected: "Frånkopplad",
    error: "Fel",
    failed: "Misslyckades",
    gateway: "Gateway",
    gatewayFailedToStart: "Gatewayen kunde inte starta",
    lastUpdate: "Senaste uppdatering",
    noneRunning: "Inga",
    notRunning: "Körs inte",
    platformDisconnected: "frånkopplad",
    platformError: "fel",
    recentSessions: "Senaste sessionerna",
    restartGateway: "Starta om gateway",
    restartGatewayConfirmMessage:
      "Detta startar om Hermes gateway-process. Anslutna kanaler och aktiva sessioner återansluts därefter.",
    restartGatewayConfirmTitle: "Starta om gateway?",
    restartingGateway: "Startar om gateway…",
    running: "Körs",
    runningRemote: "Körs (fjärransluten)",
    startFailed: "Starten misslyckades",
    starting: "Startar",
    startedInBackground: "Startad i bakgrunden — kontrollera loggarna för förlopp",
    stopped: "Stoppad",
    updateHermes: "Uppdatera Hermes",
    updateHermesConfirmMessage:
      "Detta kör hermes update och startar om gatewayen när det är klart. Aktiva sessioner behåller sin promptcache tills dess.",
    updateHermesConfirmNow: "Uppdatera nu",
    updateHermesConfirmTitle: "Uppdatera Hermes?",
    updatingHermes: "Uppdaterar Hermes…",
    waitingForOutput: "Väntar på utdata…",
  },
  sessions: {
    title: "Sessioner",
    history: "Historik",
    overview: "Översikt",
    filterChats: "Chattar",
    filterAutomation: "Automatisering",
    filterAll: "Alla",
    sourceFilter: "Sessionskälla",
    anySource: "Valfri källa",
    searchPlaceholder: "Sök i meddelandeinnehåll…",
    noSessions: "Inga sessioner ännu",
    noSessionsInFilter: "Inga sessioner i detta filter",
    noMatch: "Inga sessioner matchar din sökning",
    startConversation: "Starta en konversation så visas den här",
    noMessages: "Inga meddelanden",
    untitledSession: "Namnlös session",
    deleteSession: "Ta bort session",
    confirmDeleteTitle: "Ta bort session?",
    confirmDeleteMessage:
      "Detta tar permanent bort konversationen och alla dess meddelanden. Åtgärden kan inte ångras.",
    sessionDeleted: "Sessionen togs bort",
    failedToDelete: "Det gick inte att ta bort sessionen",
    deleteEmpty: "Ta bort tomma",
    deleteEmptyConfirmTitle: "Ta bort tomma sessioner?",
    deleteEmptyConfirmMessage:
      "Detta tar permanent bort {count} sessioner utan meddelanden. Aktiva och arkiverade sessioner hoppas över. Åtgärden kan inte ångras.",
    emptySessionsDeleted: "{count} tomma sessioner togs bort",
    failedToDeleteEmpty: "Det gick inte att ta bort tomma sessioner",
    selectSession: "Välj session",
    selectAllOnPage: "Välj alla på sidan",
    clearSelection: "Rensa markering",
    selectedCount: "{count} valda",
    deleteSelected: "Ta bort {count}",
    deleteSelectedConfirmTitle: "Ta bort {count} sessioner?",
    deleteSelectedConfirmMessage:
      "Detta tar permanent bort {count} valda sessioner och alla deras meddelanden. Åtgärden kan inte ångras.",
    selectedSessionsDeleted: "{count} sessioner togs bort",
    failedToDeleteSelected: "Det gick inte att ta bort valda sessioner",
    resumeInChat: "Fortsätt i chatt",
    newChat: "Ny chatt",
    previousPage: "Föregående sida",
    nextPage: "Nästa sida",
    roles: { user: "Användare", assistant: "Assistent", system: "System", tool: "Verktyg" },
  },
  analytics: {
    period: "Period:",
    totalTokens: "Totalt antal token",
    totalSessions: "Totalt antal sessioner",
    apiCalls: "API-anrop",
    dailyTokenUsage: "Daglig tokenanvändning",
    dailyBreakdown: "Daglig fördelning",
    perModelBreakdown: "Fördelning per modell",
    topSkills: "Mest använda färdigheter",
    skill: "Färdighet",
    loads: "Inläst av agenten",
    edits: "Hanterad av agenten",
    lastUsed: "Senast använd",
    input: "Indata",
    output: "Utdata",
    total: "Totalt",
    noUsageData: "Ingen användningsdata för denna period",
    startSession: "Starta en session för att se analys här",
    date: "Datum",
    model: "Modell",
    tokens: "Token",
    perDayAvg: "genomsnitt/dag",
    acrossModels: "fördelat på {count} modeller",
    inOut: "{input} in / {output} ut",
  },
  models: {
    modelsUsed: "Använda modeller", estimatedCost: "Beräknad kostnad", tokens: "token", sessions: "sessioner",
    avgPerSession: "genomsnitt/session", apiCalls: "API-anrop", toolCalls: "verktygsanrop",
    noModelsData: "Ingen modellstatistik för denna period", startSession: "Starta en session för att se modellstatistik här",
  },
  logs: { title: "Loggar", autoRefresh: "Uppdatera automatiskt", file: "Fil", level: "Nivå", component: "Komponent", lines: "Rader", noLogLines: "Inga loggrader hittades" },
  cron: {
    confirmDeleteMessage: "Detta tar bort jobbet från schemat. Åtgärden kan inte ångras.", confirmDeleteTitle: "Ta bort schemalagt jobb?",
    newJob: "Nytt schemalagt jobb", nameOptional: "Namn (valfritt)", namePlaceholder: "t.ex. Daglig sammanfattning", prompt: "Prompt",
    promptPlaceholder: "Vad ska agenten göra vid varje körning?", schedule: "Schema (cron-uttryck)", schedulePlaceholder: "0 9 * * *", scheduleMode: "Schema",
    scheduleModes: {
      interval: "Varje intervall", daily: "Dagligen", weekly: "Varje vecka", monthly: "Varje månad", once: "En gång", custom: "Anpassat (cron-uttryck)",
      intervalEvery: "Varje", intervalUnit: "Enhet", unitMinutes: "minuter", unitHours: "timmar", unitDays: "dagar", timeOfDay: "Tid på dagen", weekdays: "Veckodagar",
      weekdaysShort: ["Sön", "Mån", "Tis", "Ons", "Tor", "Fre", "Lör"], dayOfMonth: "Dag i månaden", onceAt: "Kör vid", customLabel: "Cron-uttryck", customPlaceholder: "0 9 * * *",
      customHint: "Cron-uttryck med fem fält (minut, timme, dag, månad, veckodag).", preview: "Skickas som", previewEmpty: "(ofullständigt)",
    },
    scheduleDescribe: { none: "—", everyMinutes: "Var {n}:e min", everyHours: "Var {n}:e timme", everyDays: "Var {n}:e dag", dailyAt: "Dagligen kl. {time}", weeklyAt: "Varje vecka på {days} kl. {time}", monthlyAt: "Varje månad den {day} kl. {time}", onceAt: "En gång kl. {time}" },
    deliverTo: "Leverera till", scheduledJobs: "Schemalagda jobb", noJobs: "Inga cron-jobb är konfigurerade. Skapa ett ovan.", last: "Senaste", next: "Nästa", pause: "Pausa", resume: "Återuppta", triggerNow: "Kör nu",
    delivery: { local: "Lokalt", telegram: "Telegram", discord: "Discord", slack: "Slack", email: "E-post", needsHomeChannel: "ange först en hemkanal", noneConfigured: "Inga meddelandeplattformar är konfigurerade. Konfigurera en under Kanaler för att leverera rapporter." },
  },
  profiles: {
    newProfile: "Ny profil", name: "Namn", namePlaceholder: "t.ex. programmerare, skribent", nameRequired: "Namn krävs",
    nameRule: "Endast gemena bokstäver, siffror, _ och -; måste börja med bokstav eller siffra; högst 64 tecken.", invalidName: "Ogiltigt profilnamn", cloneFrom: "Klona konfiguration från", cloneFromNone: "Ingen (tom)", allProfiles: "Profiler", noProfiles: "Inga profiler hittades.", defaultBadge: "standard", hasEnv: "miljö", model: "Modell", skills: "Färdigheter", rename: "Byt namn", editSoul: "Redigera SOUL.md", soulSection: "SOUL.md (personlighet/systemprompt)", soulPlaceholder: "# Så här ska agenten bete sig…", saveSoul: "Spara SOUL", soulSaved: "SOUL.md sparades", openInTerminal: "Kopiera CLI-kommando", commandCopied: "Kopierades till urklipp", copyFailed: "Det gick inte att kopiera", confirmDeleteTitle: "Ta bort profil?", confirmDeleteMessage: "Detta tar permanent bort profilen ”{name}” — konfiguration, nycklar, minnen, sessioner, färdigheter och cron-jobb. Åtgärden kan inte ångras.", created: "Skapad", deleted: "Borttagen", renamed: "Namn ändrat", activeProfile: "Aktiv profil", activeBadge: "aktiv", setActive: "Gör aktiv", activeSet: "Aktiv profil angavs", gatewayRunning: "Gateway körs", gatewayStopped: "Gateway stoppad", gatewayRunningWarning: "Den här profilens gateway körs — den stoppas.", aliasBadge: "alias", description: "Beskrivning", descriptionPlaceholder: "Vad är den här profilen bra på? Används för att dirigera kanban-uppgifter efter roll.", noDescription: "Ingen beskrivning", editDescription: "Redigera beskrivning", descriptionSaved: "Beskrivningen sparades", reviewBadge: "granskning", autoGenerate: "Generera automatiskt", generating: "Genererar…", describeFailed: "Det gick inte att generera beskrivning", distribution: "Distribution", advancedOptions: "Avancerade alternativ", cloneAll: "Klona allt (minnen, sessioner, färdigheter, tillstånd)", noSkillsOption: "Lägg inte till medföljande färdigheter", descriptionOptional: "Beskrivning (valfri)", modelOptional: "Modell (valfri)", modelInherit: "Ärv från klon/standard", modelLoading: "Läser in modeller…", modelNone: "Inga autentiserade leverantörer — ange först en nyckel", editModel: "Byt modell", modelSaved: "Modellen uppdaterades", modelSelect: "Välj en modell", actions: "Åtgärder",
  },
  pluginsPage: {
    contextEngineLabel: "Kontextmotor", dashboardSlots: "Instrumentpanelsplatser", disableRuntime: "Inaktivera", enableAfterInstall: "Aktivera efter installation", enableRuntime: "Aktivera", forceReinstall: "Tvinga ominstallation (ta först bort befintlig mapp)", headline: "Upptäck, installera, aktivera och uppdatera Hermes-pluginer (motsvarar `hermes plugins`).", identifierLabel: "Git-URL eller ägare/repo", inactive: "inaktiv", installBtn: "Installera", installHeading: "Installera från GitHub/Git-URL", installHint: "Använd förkortningen ägare/repo eller en fullständig https://- eller git@-klonings-URL. För ett plugin i en underkatalog, lägg till sökvägen: ägare/repo/sökväg/till/plugin (eller <url>#sökväg/till/plugin).", memoryProviderLabel: "Minnesleverantör", missingEnvWarn: "Ange följande under Nycklar innan pluginet kan köras:", noDashboardTab: "Ingen instrumentpanelsflik", openTab: "Öppna", orphanHeading: "Endast instrumentpanelsutökningar (ingen matchande plugin.yaml för agenten)", pluginListHeading: "Installerade pluginer", providerDefaults: "inbyggd/standard", providersHeading: "Körningspluginer för leverantörer", providersHint: "Skriver memory.provider (tomt = inbyggd) och context.engine till config.yaml. Gäller nästa session.", refreshDashboard: "Sök om instrumentpanelsutökningar", removeConfirm: "Ta bort detta plugin från ~/.hermes/plugins/?", removeHint: "Endast användarinstallerade pluginer under ~/.hermes/plugins kan tas bort.", rescanHeading: "SPA-pluginregister", rescanHint: "Sök om efter att du har lagt till filer på disken så att sidofältet på instrumentpanelen hittar nya manifest.", runtimeHeading: "Gateway-körning (YAML-pluginer)", saveProviders: "Spara leverantörsinställningar", savedProviders: "Leverantörsinställningarna sparades.", sourceBadge: "Källa", authRequired: "Autentisering krävs", authRequiredHint: "Kör detta kommando för att autentisera:", updateGit: "Git pull", versionBadge: "Version", showInSidebar: "Visa i sidofältet", hideFromSidebar: "Dölj från sidofältet",
  },
  skills: { title: "Färdigheter", searchPlaceholder: "Sök färdigheter och verktygsuppsättningar…", enabledOf: "{enabled}/{total} aktiverade", all: "Alla", categories: "Kategorier", filters: "Filter", noSkills: "Inga färdigheter hittades. Färdigheter läses in från ~/.hermes/skills/", noSkillsMatch: "Inga färdigheter matchar din sökning eller ditt filter.", skillCount: "{count} färdighet{s}", resultCount: "{count} resultat{s}", noDescription: "Ingen beskrivning tillgänglig.", toolsets: "Verktygsuppsättningar", toolsetLabel: "Verktygsuppsättningen {name}", noToolsetsMatch: "Inga verktygsuppsättningar matchar sökningen.", setupNeeded: "Konfiguration krävs", disabledForCli: "Inaktiverad för CLI", more: "+{count} till", profileSelector: "Profil", currentProfile: "nuvarande ({name})", managingProfile: "Hanterar profilen ”{name}” — växlingar gäller den profilen, inte denna instrumentpanel.", },
  config: {
    configPath: "~/.hermes/config.yaml", filters: "Filter", sections: "Avsnitt", exportConfig: "Exportera konfiguration som JSON", importConfig: "Importera konfiguration från JSON", resetDefaults: "Återställ standardvärden", resetScopeTooltip: "Återställ {scope} till standardvärden", confirmResetScope: "Återställ alla inställningar för {scope} till deras standardvärden? Detta uppdaterar bara formuläret — ändringarna skrivs inte till config.yaml förrän du trycker på Spara.", resetScopeToast: "{scope} återställdes till standardvärden — granska och spara för att behålla ändringarna", rawYaml: "Rå YAML-konfiguration", searchResults: "Sökresultat", fields: "fält", noFieldsMatch: "Inga fält matchar ”{query}”", configSaved: "Konfigurationen sparades", yamlConfigSaved: "YAML-konfigurationen sparades", failedToSave: "Det gick inte att spara", failedToSaveYaml: "Det gick inte att spara YAML", failedToLoadRaw: "Det gick inte att läsa in rå konfiguration", configImported: "Konfigurationen importerades — granska och spara", invalidJson: "Ogiltig JSON-fil",
    categories: { general: "Allmänt", agent: "Agent", terminal: "Terminal", display: "Visning", delegation: "Delegering", memory: "Minne", compression: "Komprimering", security: "Säkerhet", browser: "Webbläsare", voice: "Röst", tts: "Text till tal", stt: "Tal till text", logging: "Loggning", discord: "Discord", auxiliary: "Extra" },
  },
  env: {
    changesNote: "Ändringar sparas genast på disken. Aktiva sessioner tar automatiskt upp nya nycklar.", confirmClearMessage: "Det sparade värdet för denna variabel tas bort från din .env-fil. Åtgärden kan inte ångras i gränssnittet.", confirmClearTitle: "Rensa denna nyckel?", description: "Hantera API-nycklar och hemligheter som lagras i", hideAdvanced: "Dölj avancerat", showAdvanced: "Visa avancerat", showLess: "Visa mindre", showMore: "Visa mer", llmProviders: "LLM-leverantörer", providersConfigured: "{configured} av {total} leverantörer konfigurerade", getKey: "Hämta nyckel", notConfigured: "{count} inte konfigurerade", notSet: "Inte angiven", keysCount: "{count} nyckel{s}", enterValue: "Ange värde…", replaceCurrentValue: "Ersätt aktuellt värde ({preview})", showValue: "Visa verkligt värde", hideValue: "Dölj värde", customTitle: "Egna nycklar", customHint: "Godtyckliga miljövariabler som lagras i din .env och som Hermes inte känner igen. Använd dem för att tillföra miljövariabler för färdigheter, MCP-servrar eller egna verktyg.", customConfigured: "{count} egen nyckel/egna nycklar angivna", addCustomKey: "Lägg till egen nyckel", customKeyName: "Variabelnamn", customKeyNamePlaceholder: "t.ex. MY_SERVICE_API_KEY", add: "Lägg till", invalidKeyName: "Använd bara bokstäver, siffror och understreck (måste börja med en bokstav eller ett understreck).",
  },
  oauth: {
    title: "Inloggningar för leverantörer (OAuth)", providerLogins: "Inloggningar för leverantörer (OAuth)", description: "{connected} av {total} OAuth-leverantörer är anslutna. Använd Logga in för flöden som stöds av instrumentpanelen; CLI-kommandon är fortfarande tillgängliga för extern konfiguration eller reservkonfiguration.", connected: "Ansluten", expired: "Har löpt ut", notConnected: "Inte ansluten. Använd Logga in när det är möjligt, eller kör {command} i en terminal.", runInTerminal: "i en terminal.", noProviders: "Inga OAuth-kompatibla leverantörer hittades.", login: "Logga in", disconnect: "Koppla från", managedExternally: "Hanteras externt", copied: "Kopierat ✓", copyCode: "Kopiera kod", copyFailed: "Det gick inte att kopiera automatiskt. Markera koden och kopiera den manuellt.", cli: "Kopiera", copyCliCommand: "Kopiera CLI-kommando (extern/reserv)", connect: "Anslut", sessionExpires: "Sessionen löper ut om {time}", sessionExpiredNoError: "Inloggningen löpte ut innan leverantören nåddes. Det brukar innebära att inloggningssidan stannade i den öppnade fliken (fel på serversidan) — slutför inloggningen där och klicka sedan på Försök igen. Om problemet kvarstår, använd en API-nyckel eller CLI-reserven i stället.", initiatingLogin: "Startar inloggningsflöde…", exchangingCode: "Byter kod mot token…", connectedClosing: "Ansluten! Stänger…", loginFailed: "Inloggningen misslyckades.", sessionExpired: "Sessionen har löpt ut. Klicka på Försök igen för att starta en ny inloggning.", reOpenAuth: "Öppna autentiseringssidan igen", reOpenVerification: "Öppna verifieringssidan igen", submitCode: "Skicka kod", pasteCode: "Klistra in auktoriseringskod (#state-suffix går bra)", waitingAuth: "Väntar på att du auktoriserar i webbläsaren…", enterCodePrompt: "En ny flik öppnades. Ange denna kod om du blir ombedd:", pkceStep1: "En ny flik öppnades på claude.ai. Logga in och klicka på Auktorisera.", pkceStep2: "Kopiera auktoriseringskoden som visas efter auktorisering.", pkceStep3: "Klistra in den nedan och skicka.", flowLabels: { pkce: "Inloggning i webbläsare (PKCE)", device_code: "Enhetskod", external: "Externt CLI" }, expiresIn: "löper ut om {time}",
  },
  language: { switchTo: "Byt språk" },
  theme: { title: "Tema", switchTheme: "Byt tema", fontTitle: "Typsnitt", fontDefault: "Temats standard", fontDefaultHint: "Använd det aktiva temats typsnitt", fontSans: "Sans serif", fontSerif: "Serif", fontMono: "Fast bredd" },
  achievements: {
    hero: { kicker: "Agentbaserat poängsystem", title: "Hermes-prestationer", subtitle: "Samlarbara Hermes-märken som förtjänas genom verklig sessionshistorik. Kända ej slutförda prestationer visas som Upptäckta; hemliga prestationer förblir dolda tills ett första matchande beteende förekommer.", scan_subtitle: "Genomsöker Hermes sessionshistorik. Den första genomsökningen kan ta 5–10 sekunder för omfattande historik." },
    actions: { rescan: "Sök igen" }, stats: { unlocked: "Upplåsta", unlocked_hint: "förtjänade märken", discovered: "Upptäckta", discovered_hint: "kända, ännu inte förtjänade", secrets: "Hemligheter", secrets_hint: "dolda till första signal", highest_tier: "Högsta nivå", highest_tier_hint: "Brons → Silver → Guld → Diamant → Olympisk", latest: "Senaste", latest_hint_empty: "kör Hermes mer", none_yet: "Inga ännu" }, state: { unlocked: "Upplåst", discovered: "Upptäckt", secret: "Hemlig" }, tier: { target: "Mål {tier}", hidden: "Dold", complete: "Slutförd", objective: "Mål" }, progress: { hidden: "dold" },
    scan: { building_headline: "Skapar prestationsprofil…", building_detail: "Läser sessioner, verktygsanrop, modellmetadata och upplåsningstillstånd.", starting_headline: "Startar genomsökning av prestationer…", progress_detail: "Genomsökte {scanned} av {total} sessioner · {pct} %. Märken låses upp när mer historik läses in.", idle_detail: "Läser sessioner, verktygsanrop, modellmetadata och upplåsningstillstånd. Märken visas här när de låses upp." },
    guide: { tiers_header: "Nivåer", secret_header: "Hemliga prestationer", secret_body: "Hemligheter döljer sin exakta utlösare. När Hermes ser en relaterad signal blir kortet upptäckt och visar sitt krav.", scan_status_header: "Status för genomsökning", scan_status_body: "Hermes genomsöker lokal historik en gång, sedan visas kort automatiskt. Inget har fastnat om detta tar några sekunder.", what_scanned_header: "Vad som genomsöks", what_scanned_body: "Sessioner, verktygsanrop, modellmetadata, fel, prestationer och lokalt upplåsningstillstånd." },
    card: { share_title: "Dela denna prestation", share_label: "Dela {name}", share_text: "Dela", how_to_reveal: "Så låser du upp", what_counts: "Vad som räknas", evidence_label: "Bevis", evidence_session_fallback: "session", no_evidence: "Inga bevis ännu" }, latest: { header: "Senaste upplåsningar" }, empty: { no_secrets_header: "Inga dolda hemligheter kvar i denna genomsökning.", no_secrets_body: "Ledtråd: hemligheter börjar ofta med ovanliga fel eller vanor hos avancerade användare — portkonflikter, behörighetshinder, saknade miljövariabler, YAML-misstag, Docker-kollisioner, användning av återställning/kontrollpunkter, cacheträffar eller små rättningar efter mycket röd text." }, filters: { all_categories: "Alla", visibility_all: "alla", visibility_unlocked: "upplåsta", visibility_discovered: "upptäckta", visibility_secret: "hemliga" },
    share: { dialog_label: "Dela prestation", header: "Dela: {name}", close: "Stäng", rendering: "Renderar…", card_alt: "Delningskort för {name}", error_generic: "Något gick fel.", x_title: "Öppnar X med ett förifyllt inlägg", x_button: "Dela på X", copy_title: "Kopiera bilden för att klistra in den i ditt inlägg", copy_button: "Kopiera bild", copied: "Kopierat ✓", download_button: "Hämta PNG", hint: "Dela på X öppnar ett förifyllt inlägg på en ny flik. Klicka först på Kopiera bild om du vill bifoga 1200×630-märket — X låter dig klistra in det direkt i inläggsredigeraren. Hämta PNG sparar filen för användning var som helst.", clipboard_unsupported: "Kopiering av bilder till urklipp stöds inte i denna webbläsare — använd Hämta i stället.", tweet_text: "Låste just upp {tier_part}”{name}” i Hermes Agent ☤" },
  },
  kanban: {
    loading: "Läser in kanban-tavla…", loadFailed: "Det gick inte att läsa in kanban-tavlan: ", loadFailedHint: "Serverdelen skapar automatiskt kanban.db vid första läsningen. Om problemet kvarstår, kontrollera instrumentpanelens loggar.", board: "Tavla", newBoard: "+ Ny tavla", newBoardTitle: "Ny tavla", newBoardDescription: "Tavlor låter dig separera orelaterade arbetsflöden — en per projekt, repo eller område. Arbetare på en tavla ser aldrig en annan tavlas uppgifter.", slug: "Slug", slugHint: "— gemener, bindestreck, t.ex. atm10-server", displayName: "Visningsnamn", displayNameHint: "(valfritt)", description: "Beskrivning", descriptionHint: "(valfritt)", icon: "Ikon", iconHint: "(ett tecken eller emoji)", switchAfterCreate: "Växla till denna tavla efter att den har skapats", cancel: "Avbryt", creating: "Skapar…", createBoard: "Skapa tavla", search: "Sök", filterCards: "Filtrera kort…", tenant: "Klient", allTenants: "Alla klienter", assignee: "Tilldelad", allProfiles: "Alla profiler", showArchived: "Visa arkiverade", lanesByProfile: "Banor per profil", nudgeDispatcher: "Påminn dirigenten", refresh: "Uppdatera", selected: "valda", complete: "Slutför", archive: "Arkivera", apply: "Tillämpa", clear: "Rensa", createTask: "Skapa uppgift i denna kolumn", noTasks: "— inga uppgifter —", unassigned: "inte tilldelad", needsAssignee: "Behöver en tilldelad", needsAssigneeHint: "Beroenden är uppfyllda, men dirigenten hoppar över den här uppgiften tills du tilldelar en profil.", untitled: "(namnlös)", loadingDetail: "Läser in…", addComment: "Lägg till en kommentar… (Retur för att skicka)", comment: "Kommentar", status: "Status", workspace: "Arbetsyta", skills: "Färdigheter", createdBy: "Skapad av", result: "Resultat", comments: "Kommentarer", events: "Händelser", runHistory: "Körhistorik", workerLog: "Arbetarlogg", loadingLog: "Läser in logg…", noWorkerLog: "— ingen arbetarlogg ännu (uppgiften har inte startats eller loggen har roterats bort) —", noDescription: "— ingen beskrivning —", noComments: "— inga kommentarer —", edit: "redigera", save: "Spara", dependencies: "Beroenden", parents: "Föräldrar:", children: "Underordnade:", none: "inga", addParent: "— lägg till förälder —", addChild: "— lägg till underordnad —", removeDependency: "Ta bort beroende", block: "Blockera", unblock: "Avblockera", notifyHomeChannels: "Avisera hemkanaler", diagnostics: "Diagnostik", hide: "Dölj", show: "Visa", attention: "Uppmärksamhet", tasksNeedAttention: "uppgifter behöver uppmärksamhet", taskNeedsAttention: "1 uppgift behöver uppmärksamhet", diagnostic: "diagnostisk", open: "Öppna", close: "Stäng (Esc)", reassignTo: "Tilldela om till:", copied: "Kopierat", copyCommand: "Kopiera kommando till urklipp", reclaim: "Återta", reassign: "Tilldela om", renderingError: "Kanban-fliken fick ett renderingsfel", reloadView: "Läs in vyn igen", wsAuthFailed: "WebSocket-autentisering misslyckades — läs in sidan igen för att uppdatera sessionstoken.", markDone: "Markera {n} uppgift(er) som klara?", markArchived: "Arkivera {n} uppgift(er)?", warning: "Varning", phantomIds: "Spök-id:n:", active: "aktiva", ended: "avslutade", noProfile: "(ingen profil)", showAllAttempts: "Visa alla försök", sendingUpdates: "Skickar uppdateringar till", sendNotifications: "Skicka aviseringar om slutförda/blockerade/uppgivna till", archiveBoardConfirm: "Arkivera tavlan ”{name}”? Den flyttas till boards/_archived/ så att du kan återställa den senare. Uppgifter på denna tavla visas inte längre någonstans i gränssnittet.", archiveBoardTitle: "Arkivera denna tavla", boardSwitcherHint: "Tavlor låter dig separera orelaterade arbetsflöden", taskCreatedWarning: "Uppgiften skapades, men: ", moveFailed: "Flytten misslyckades: ", bulkFailed: "Massåtgärd: ", completionBlockedHallucination: "⚠ Slutförande blockerat — spökkorts-id:n", suspectedHallucinatedReferences: "⚠ Text hänvisade till spökkorts-id:n", pickProfileFirst: "Välj först en profil.", unblockedMessage: "Avblockerade {id}. Uppgiften är klar för nästa körning.", unblockFailed: "Det gick inte att avblockera: ", reclaimedMessage: "Återtog {id}. Uppgiften är klar igen.", reclaimFailed: "Det gick inte att återta: ", reassignedMessage: "Tilldelade om {id} till {profile}.", reassignFailed: "Det gick inte att tilldela om: ", selectForBulk: "Välj för massåtgärder", clickToEdit: "Klicka för att redigera", clickToEditAssignee: "Klicka för att redigera tilldelad", emptyAssignee: "(tomt = ta bort tilldelning)",
    columnLabels: { triage: "Triage", todo: "Att göra", scheduled: "Schemalagd", ready: "Klar", running: "Pågår", blocked: "Blockerad", done: "Klar", archived: "Arkiverad" },
    columnHelp: { triage: "Råa idéer — en speciferare utvecklar specifikationen", todo: "Väntar på beroenden eller tilldelning", scheduled: "Väntar på en känd tidsfördröjning eller schemalagd uppföljning", ready: "Beroenden är uppfyllda; tilldela en profil för att skicka", running: "Övertagen av en arbetare — pågår", blocked: "Arbetaren bad om mänsklig inmatning", done: "Slutförd", archived: "Arkiverad" },
    confirmDone: "Markera denna uppgift som klar? Arbetarens anspråk släpps och beroende underordnade blir klara.", confirmArchive: "Arkivera denna uppgift? Den försvinner från standardvyn för tavlan.", confirmBlocked: "Markera uppgiften som blockerad? Arbetarens anspråk släpps.", confirmScheduled: "Flytta uppgiften till Schemalagd? Använd detta vid kända tidsfördröjningar i stället för mänskliga blockerare.", confirmDoneMany: "Markera {n} uppgifter som klara? Arbetarnas anspråk släpps och beroende underordnade blir klara.", confirmArchiveMany: "Arkivera {n} uppgifter? De försvinner från standardvyn för tavlan.", confirmBlockedMany: "Markera {n} uppgifter som blockerade? Arbetarnas anspråk släpps.", completionSummary: "Slutförandesammanfattning för {label}. Den lagras som uppgiftens resultat.", completionSummaryRequired: "En slutförandesammanfattning krävs innan en uppgift kan markeras som klar.", triagePlaceholder: "Grov idé — AI gör en specifikation…", taskTitlePlaceholder: "Ny uppgiftstitel…", specifier: "specificerare", assigneePlaceholder: "tilldelad", priority: "Prioritet", skillsPlaceholder: "färdigheter (valfria, kommaseparerade): translation, github-code-review", noParent: "— ingen förälder —", workspacePathDir: "arbetsytans sökväg (krävs, t.ex. ~/projects/min-app)", workspacePathOptional: "arbetsytans sökväg (valfri, härleds från tilldelad om tom)", logTruncated: "(visar de senaste 100 kB — fullständig logg på ", logAt: ")", newTaskTitle: "Ny uppgift — {column}", taskTitleLabel: "Titel", assigneeLabel: "Tilldelad", assigneeLabelHint: "(tomt = dirigenten väljer)", skillsLabel: "Färdigheter", skillsLabelHint: "(valfria, kommaseparerade)", parentLabel: "Föräldrauppgift", parentLabelHint: "(underordnad förblir blockerad tills föräldern är klar)", create: "Skapa", boardSettings: "Inställningar", boardSettingsTitle: "Tavlinställningar — namn, beskrivning och standardprojektmapp som nya uppgifter ärver", boardSettingsTitleFor: "Tavlinställningar — {name}", projectDirectoryOverrideHint: "Nya uppgifter ärver detta som standardarbetsyta; varje uppgift kan fortfarande åsidosätta den i skapadialogen.", saving: "Sparar…", commentHint: "Kommentarer når arbetaren vid nästa körning eller kanban_show() — du behöver inte blockera uppgiften först.", commentHintTitle: "Kommentarer är kanalen för att prata med en uppgifts arbetare. De hamnar direkt i tråden — du behöver inte blockera uppgiften först. En pågående arbetare läser tråden vid nästa kanban_show() eller återstart; blockering används bara när du vill att arbetaren ska STOPPA och vänta på din inmatning.", trash: { confirmTitle: "Ta bort uppgift?", confirmManyTitle: "Ta bort {n} uppgifter?" },
  },
});
