<?php
return [
    /**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */
    'audit-log' => 'Revisionslogg',
    'articles' => 'Artiklar',
    'applications' => 'Ansökningar',
    'bans-log' => 'Avstängningslogg',
    'blocks' => 'Blockeringar',
    'bot' => 'Bot',
    'bots' => 'Botar',
    'chat' => 'Chatt',
    'config-manager' => 'Konfigurationshanterare',
    'dashboard' => 'Administrationsöversikt',
    'failed-login-log' => 'Misslyckad inloggningslogg',
    'flush-ghost-peers' => 'Rensa spökpeers',
    'forums' => 'Forum',
    'frontend' => 'Användargränssnitt',
    'general-tools' => 'Allmänna verktyg',
    'groups' => 'Grupper',
    'invites-log' => 'Inbjudningslogg',
    'laravel-log' => 'Laravel-logg',
    'links' => 'Länkar',
    'logs' => 'Loggar',
    'mass-pm' => 'Massutskick av privata meddelanden',
    'mass-validate-users' => 'Massvaliderar användare',
    'moderation' => 'Moderering',
    'pages' => 'Sidor',
    'please-moderate' => 'Granska den här torrenten!',
    'polls' => 'Opinionsundersökningar',
    'reports-log' => 'Rapportlogg',
    'rss' => 'RSS',
    'staff-dashboard' => 'Administrationspanel',
    'torrent-categories' => 'Torrentkategorier',
    'torrent-moderation' => 'Torrentmoderering',
    'torrent-tools' => 'Torrentverktyg',
    'torrent-types' => 'Torrenttyper',
    'torrents' => 'Torrenter',
    'user-gifting' => 'Gåvor till användare',
    'user-notes' => 'Logg över användaranteckningar',
    'user-search' => 'Användarsökning',
    'user-tools' => 'Användarverktyg',
    'warnings-log' => 'Varningsloggen',
    'you-have' => 'Du har',
    'possible-leech-cheaters' => 'Eventuella fuskare',
    'chat-tools' => 'Chattverktyg',
    'flush-chat' => 'Töm chattrutan',
    'seedboxes' => 'Registrerade seedboxar',
    'application' => 'Ansökan',
    'application-type' => 'Typ',
    'application-image-proofs' => 'Bildbevis',
    'application-referrer' => 'Hänvisare',
    'article-content' => 'Innehåll',
    'blocked-ips' => 'Blockerade IP-adresser',
    'bon-exchange' => 'BON-växling',
    'bon-earnings' => 'BON-intäkter',
    'gifts-log' => 'Gåvologg',
    'link' => 'Länk',
    'mass-email' => 'Massutskick via e-post',
    'media-languages-desc' => '(Språk som används för att fylla språklistor för undertexter, ljud etc.)',
    'moderation-since' => 'Modererad den',
    'notes' => 'Anteckningar',
    'page' => 'Sida',
    'passkeys' => 'Passkeys',
    'rooms' => 'Rum',
    'status' => 'Status',
    'statuses' => 'Status',
    'ticket-categories' => 'Ärendekategorier',
    'ticket-category' => 'Ärendekategori',
    'ticket-priorities' => 'Ärendeprioriteringar',
    'ticket-priority' => 'Ärendeprioritet',
    'torrent-resolutions' => 'Torrentupplösningar',
];
